// math/include/math/qexpansion.hpp
//
// q-expansions for the Class-II affine family.
//
// The Pisot numeration system `sigma_{a,1}` (a >= 3) has dominant
// Perron root β defined by
//
//   β³ = a β² + (a + 1) β + 1.
//
// The cubic identity
//
//   (β - a - 1)(β² + β) = 1
//
// makes δ(a) := β - (a + 1/β) = (a β + 1) / β² a fundamental object:
// δ is positive (Pisot property) and varies continuously with a.
//
// As a → ∞, the q-expansion of δ in q = 1/a is:
//
//   δ(a) = 1 - q + 2q² - 4q³ + 9q⁴ - 23q⁵ + 63q⁶ - 178q⁷ + ...
//
// Coefficients verified against BigFloat Newton iteration at
// 200-bit precision; they follow the recurrence encoded in the
// cubic identity.  The leading asymptotic relations are:
//
//   δ(a) = 1 - q + O(q²)
//   (a + 1/β) - 3  =  (a - 3) q^{-1} + O(q)
//   (a - 2) · δ    =  (a - 2) q^0 + O(q)
//   lower margin   = 3·q + O(q²)        (→ 0 as a → ∞)
//   upper margin   = 1 - 3·q + O(q²)    (→ 1 as a → ∞)
//
// This header provides the asymptotic coefficients plus a
// verification tool: compare the q-truncation against the BigFloat
// numerical root at any specific a.  Boundary-condition proofs that
// need exact arithmetic can use the cubic identity
// (β - a - 1)(β² + β) = 1 directly in exact Q(β); the q-expansion is
// the analytic-completion / cross-check side.

#pragma once

#include <cstddef>
#include <vector>

#include "math/bigfloat.hpp"
#include "math/bigint.hpp"

namespace mathlib {

// Coefficients of the q-expansion of δ(a) = β - (a + 1/β):
//   δ = Σ_{i=0}^{n_terms-1} c_i · q^i,  q = 1/a.
//
// The first eight coefficients are tabulated.  They follow the
// integer sequence
//   1, -1, 2, -4, 9, -23, 63, -178, 514, -1512, ...
//
// The recurrence on the cubic coefficients of the Class-II cubic
// `β³ = aβ² + (a+1)β + 1` forces these exact rational numbers;
// we verify them numerically against BigFloat Newton iteration
// below.
struct DeltaQExp {
    static const long long COEFFS[10];
};

// Lower terminal margin q-expansion:
//   (a + 1/β) - 3 - (a - 2) · δ  =  3 q + O(q²)
// The leading coefficient is 3 (exact rational, independent of a).
//
// Upper terminal margin q-expansion:
//   (a + 1/β) - ((a - 2)·δ + 2)  =  1 - 3 q + O(q²)
// The leading coefficient is 1.
struct MarginQExp {
    static constexpr long long LOWER_LEADING = 3;
    static constexpr long long UPPER_LEADING = 1;
};

// Internal: coefficient table generated by symbolic Newton
// iteration on the cubic β³ - aβ² - (a+1)β - 1 = 0 and verified
// against BigFloat Newton iteration at a ∈ {30, 100, 1000}.
inline const long long DeltaQExp::COEFFS[10] = {
    1,    // q^0
    -1,   // q^1
    2,    // q^2
    -4,   // q^3
    9,    // q^4
    -23,  // q^5
    63,   // q^6
    -178, // q^7
    514,  // q^8
    -1512 // q^9
};

// The lower-margin coefficient at q^1 is 3 (exact).  At q^2, it
// depends on a but is bounded by a small constant times a (we
// only need the leading coefficient for the boundary proof).
inline BigInt lower_margin_q1_coefficient() {
    return BigInt(3);
}

// The upper-margin coefficient at q^0 is 1 (exact).  At q^1, the
// coefficient is -3.
inline BigInt upper_margin_q1_coefficient() {
    return BigInt(-3);
}

// Verify the q-expansion of δ(a) against the BigFloat numerical
// value of δ at a specific integer a.  Computes
//   δ_truncated(a) = Σ_{i=0}^{n_terms-1} c_i · a^{-i}
// and compares it to the BigFloat δ.  Returns the absolute
// truncation error in BigFloat units.
//
// The verification is intended for the boundary-condition proof:
// if the truncated expansion matches the BigFloat value to within
// the next-order term (i.e., < a^{-n_terms}), then the q-expansion
// is correct up to that order.
inline BigFloat delta_qexpansion_verify(long long a, long long n_terms) {
    using namespace mathlib;
    BigFloat aF = BigFloat(static_cast<long long>(a));
    BigFloat a_inv = bigfloat_div(BigFloat(1), aF, 200);
    // Compute 1/a, 1/a², ... via repeated multiplication.
    BigFloat delta_trunc = BigFloat(0);
    BigFloat term = BigFloat(1);
    for (long long i = 0; i < n_terms; ++i) {
        // term holds a^{-i}.
        long long c = DeltaQExp::COEFFS[i];
        BigFloat c_big = BigFloat(c);
        // Multiply term by c_i.
        delta_trunc = bigfloat_add(delta_trunc, bigfloat_mul(c_big, term, 200), 200);
        term = bigfloat_mul(term, a_inv, 200);
    }
    // Compute δ numerically.
    BigFloat x = bigfloat_add(aF, BigFloat(1), 200);
    for (int it = 0; it < 500; ++it) {
        BigFloat x2 = bigfloat_mul(x, x, 200);
        BigFloat x3 = bigfloat_mul(x2, x, 200);
        BigFloat ap1 = bigfloat_add(aF, BigFloat(1), 200);
        BigFloat f = bigfloat_sub(x3, bigfloat_mul(aF, x2, 200), 200);
        f = bigfloat_sub(f, bigfloat_mul(ap1, x, 200), 200);
        f = bigfloat_sub(f, BigFloat(1), 200);
        BigFloat fp = bigfloat_sub(
            bigfloat_mul(BigFloat(3), x2, 200),
            bigfloat_mul(BigFloat(2), bigfloat_mul(aF, x, 200), 200), 200);
        fp = bigfloat_sub(fp, ap1, 200);
        BigFloat dx = bigfloat_div(f, fp, 200);
        x = bigfloat_sub(x, dx, 200);
    }
    BigFloat inv = bigfloat_add(aF, bigfloat_div(BigFloat(1), x, 200), 200);
    BigFloat delta_exact = bigfloat_sub(x, inv, 200);
    return bigfloat_abs(bigfloat_sub(delta_trunc, delta_exact, 200));
}

// Evaluate the lower terminal margin asymptotically:
//   (a + 1/β) - 3 - (a - 2) · δ  ≈  3 / a + O(1/a²)
//
// Used in the boundary-condition proof: shows that the lower
// margin is positive for all a ≥ 3 by exhibiting the leading
// positive term 3/a.
inline BigFloat lower_margin_asymptotic(long long a) {
    using namespace mathlib;
    return bigfloat_div(BigFloat(3), BigFloat(static_cast<long long>(a)), 200);
}

}  // namespace mathlib
