#include <cassert>
#include <cstddef>
#include <cstdio>
#include <vector>

#include "ravel/proof/graded_core_descent.hpp"

int main() {
    using namespace ravel::proof;
    std::size_t checked = 0;
    for (std::size_t n = 3; n <= 10; ++n) {
        DisplacementSumCatalogue catalogue(n);
        const auto& atoms = catalogue.atoms();
        for (std::size_t i = 0; i < atoms.size(); ++i) {
            assert(catalogue.grade(atoms[i]) == 1);
            ++checked;
            for (std::size_t j = i; j < atoms.size(); ++j) {
                std::vector<long long> sum(n);
                for (std::size_t k = 0; k < n; ++k)
                    sum[k] = atoms[i][k] + atoms[j][k];
                assert(catalogue.grade(sum) <= 2);
                ++checked;
            }
        }
    }

    // A graph-generic phase cover: vertices 0 and 1 reach the directly
    // decomposable phase 2 in at most two steps.
    const std::vector<std::vector<std::size_t>> successors{{1}, {2}, {2}};
    const auto phase = derive_phase_aware_grade_reduction(
        successors.size(),
        [&](std::size_t v) { return successors[v]; },
        [&](std::size_t v) { return v == 2; });
    assert(phase.complete);
    assert(phase.maximum_hops == 2);
    assert(phase.paths.size() == 2);

    // Transition-compatible decomposition on a two-state recurrent graph.
    // The active summand follows a predicted-core edge while the remainder
    // follows the homogeneous carry update.
    {
        const std::size_t n = 3;
        DisplacementSumCatalogue catalogue(n);
        struct V { ravel::nbonacci_margin::LabelPair pair; std::vector<long long> x; };
        const auto atoms = catalogue.atoms();
        // Find a grade-two state and one compatible successor generated by an
        // actual predicted-core active summand.
        bool found = false;
        for (const auto& a : atoms) {
            for (const auto& b : atoms) {
                std::vector<long long> x(n);
                for (std::size_t k = 0; k < n; ++k) x[k] = a[k] + b[k];
                for (std::size_t i = 0; i < n && !found; ++i)
                    for (std::size_t j = 0; j < n && !found; ++j) {
                        ravel::nbonacci_margin::LabelPair pair{i,j};
                        const auto ws = catalogue.derive_one_stage(pair, x);
                        if (ws.empty()) continue;
                        ravel::nbonacci_margin::CoreState active{pair, ws.front().active_descriptor};
                        const auto succ = ravel::nbonacci_margin::predicted_core_successors(n, active);
                        if (succ.empty()) continue;
                        const auto target_active = *succ.begin();
                        const auto rem2 = ravel::nbonacci_margin::forward_displacement(ws.front().remainder, 0);
                        const auto act2 = ravel::nbonacci_margin::displacement_from_descriptor(n, target_active.displacement);
                        std::vector<long long> y(n);
                        for (std::size_t k = 0; k < n; ++k) y[k] = act2[k] + rem2[k];
                        std::vector<V> vs{{pair,x},{target_active.pair,y}};
                        std::vector<std::vector<std::size_t>> es{{1},{}};
                        // The reverse edge need not be compatible; this still
                        // exercises exact affine replay and relation building.
                        const auto source_witness = ws.front();
                        GradeDescentWitness target_witness{
                            source_witness.source_grade,
                            source_witness.remainder_grade,
                            target_active.displacement,
                            act2,
                            rem2,
                            source_witness.phase};
                        assert(compatible_grade_descent_edge(
                            n, pair, source_witness,
                            target_active.pair, target_witness));
                        const auto tr = derive_transition_compatible_grade_descent(
                            catalogue, vs.size(),
                            [&](std::size_t v){ return es[v]; },
                            [&](std::size_t v){ return vs[v].pair; },
                            [&](std::size_t v){ return vs[v].x; });
                        assert(tr.decomposition_law_replayed);
                        found = true;
                    }
            }
        }
        assert(found);
    }

    std::printf("graded core descent PASS checks=%zu maxPhaseHops=%zu\\n",
                checked, phase.maximum_hops);
}
