import Mathlib.Algebra.Polynomial.Basic
import Mathlib.Algebra.BigOperators.Group.Finset.Defs
import Mathlib.Tactic

namespace Ravel.Polynomial

open scoped BigOperators

/-- Reusable closure rule for the finite geometric sum generated by the
first-order determinant recurrence `D (n + 1) = X * D n + 1`. -/
theorem one_add_X_mul_sum_range_pow (n : ℕ) :
    1 + (Polynomial.X : Polynomial ℤ) *
          (∑ k ∈ Finset.range n, (Polynomial.X : Polynomial ℤ) ^ k) =
      ∑ k ∈ Finset.range (n + 1), (Polynomial.X : Polynomial ℤ) ^ k := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [Finset.sum_range_succ]
      rw [mul_add]
      rw [Finset.sum_range_succ, pow_succ, ← ih]
      ring

/-- Reusable parity normalization for the even exponent emitted by the
characteristic-cofactor sign calculation. Two variants are registered:
the polymorphic one for simp-set firing, and the concrete-`Polynomial ℤ`
one for the engine's direct emission. -/
theorem neg_one_pow_twice {R : Type*} [CommRing R] (n : ℕ) :
    (-1 : R) ^ (n * 2) = 1 := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [show (n + 1) * 2 = n * 2 + 2 by ring, pow_add, ih]
      ring

@[simp] theorem neg_one_pow_twice_int (n : ℕ) :
    (-1 : Polynomial ℤ) ^ (n * 2) = 1 :=
  neg_one_pow_twice n

@[simp] theorem neg_one_pow_succ_mul_self_int (n : ℕ) :
    (-1 : Polynomial ℤ) ^ (n + 1) * (-1 : Polynomial ℤ) ^ n = -1 := by
  rw [← pow_add]
  rw [show n + 1 + n = n * 2 + 1 by omega]
  rw [pow_succ, neg_one_pow_twice_int]
  ring

end Ravel.Polynomial
