-- Deep pivot tree for the universal n-bonacci characteristic-polynomial proof.
-- Declarative data only. C++ owns execution and validation; Lean owns trust.

local function course(id, title, method, success, outputs, next_on_success, next_on_failure, failure_signatures)
  return {
    id = id, title = title, method = method, success = success,
    outputs = outputs or {}, next_on_success = next_on_success or {},
    next_on_failure = next_on_failure or {}, failure_signatures = failure_signatures or {},
  }
end

return {
  schema_version = 1,
  id = "nbonacci.universal.strategy_tree",
  theorem_schema = "ravel.proof.nbonacci_charpoly_schema",
  policy = {
    stop_only_when = {
      "Lean accepts universal_theorem without sorry/admit/axiom",
      "all generated files are deterministic under a clean rerun",
      "finite mutation tests reject altered maps, signs, and entries",
    },
    on_block = "classify failure, preserve artifacts, choose first untried compatible course",
    forbidden_shortcuts = {
      "finite enumeration presented as universal proof",
      "opaque generated Lean strings supplied by Lua",
      "trusting C++ determinant output as a Lean theorem",
      "weakening theorem by inserting a concrete upper bound",
    },
  },

  obligations = {
    characteristic_minor_maps = {
      objective = "Transport the two nonzero first-row cofactors to q_matrix and r_matrix for arbitrary n.",
      courses = {
        course("cm.direct_fin_equiv", "Direct Fin equivalences",
          "Generate explicit erase-index equivalences for each deleted row/column and prove entry preservation by interval case splits.",
          "Standalone Lean file proves both Matrix.minor equivalences for arbitrary n.",
          {"lean/generated/characteristic_minor_maps_direct.lean", "reports/characteristic_minor_maps_direct.txt"},
          {"characteristic_cofactor_split"}, {"cm.block_decomposition", "cm.reindex_library"},
          {"Fin arithmetic normalization stalls", "simp cannot establish transported index equality"}),
        course("cm.block_decomposition", "Block decomposition",
          "Rewrite the characteristic matrix as a 1+(n-1) block matrix and use determinant/block lemmas, avoiding explicit global minor reindexing.",
          "Lean derives the two cofactor matrices from block projections.",
          {"lean/generated/characteristic_minor_maps_block.lean"},
          {"characteristic_cofactor_split"}, {"cm.laplace_sparse", "cm.custom_erase_index"},
          {"Mathlib block determinant lemma hypotheses mismatch", "dependent block dimensions become unwieldy"}),
        course("cm.reindex_library", "Mathlib reindex route",
          "Search adjoining Mathlib Matrix/Fin sources for existing erase, succAbove, predAbove, and determinant reindex lemmas; instantiate rather than regenerate maps.",
          "A minimal proof uses library equivalences and survives n=2 boundary cases.",
          {"reports/mathlib_reindex_inventory.md", "lean/generated/characteristic_minor_maps_library.lean"},
          {"characteristic_cofactor_split"}, {"cm.custom_erase_index"},
          {"required lemma absent", "library lemma has incompatible orientation"}),
        course("cm.custom_erase_index", "Local erase-index library",
          "Add a reusable Lean module defining eraseIndexEquiv, inverse laws, order behavior, and minor transport once for all matrix families.",
          "Generic local theorem transports any entry rule through deletion.",
          {"lean/Ravel/Matrix/EraseIndex.lean", "lean/generated/characteristic_minor_maps_custom.lean"},
          {"characteristic_cofactor_split", "q_minor_reduction"}, {"cm.permutation_certificate"},
          {"dependent equality proof explosion", "performance regression in simplifier"}),
        course("cm.laplace_sparse", "Sparse Laplace theorem",
          "Prove a project-local sparse-row Laplace lemma that takes the list of nonzero columns and their minors, reducing both transport obligations to sparse support facts.",
          "Characteristic determinant split follows without full minor equality everywhere.",
          {"lean/Ravel/Matrix/SparseLaplace.lean"},
          {"characteristic_cofactor_split"}, {"cm.permutation_certificate"},
          {"support enumeration still requires difficult Fin cases"}),
        course("cm.permutation_certificate", "Permutation certificate",
          "C++ emits explicit symbolic permutations and inverse equations; Lean checks permutation matrices and determinant invariance under row/column permutation.",
          "Each cofactor is permutation-similar/equivalent to the target matrix.",
          {"lua/generated/characteristic_minor_permutations.lua", "lean/generated/characteristic_minor_permutation.lean"},
          {"characteristic_cofactor_split"}, {"cm.entry_extensionality"},
          {"sign accounting under permutations remains unresolved"}),
        course("cm.entry_extensionality", "Entry extensionality fallback",
          "Represent matrices as functions on Nat with bounds, prove bounded extensional equality, then bridge once to Fin matrices.",
          "Nat-indexed transport theorem compiles and bridge lemma is reusable.",
          {"lean/Ravel/Matrix/BoundedNat.lean"},
          {"characteristic_cofactor_split"}, {},
          {"Fin bridge becomes harder than original transport"}),
      },
    },

    r_triangular = {
      objective = "Prove det(r_matrix n)=(-1)^(n-1) universally.",
      courses = {
        course("rt.triangular_api", "Triangular API", "Prove lower-triangular support and use Matrix.det_of_lowerTriangular.",
          "Lean computes determinant as diagonal product.", {"lean/generated/r_triangular_api.lean"},
          {"polynomial_closure"}, {"rt.inductive_expansion", "rt.unitriangular_factor"}),
        course("rt.inductive_expansion", "Last-row induction", "Expand along the last row and identify the remaining principal minor recursively.",
          "Induction closes with n=2 base.", {"lean/generated/r_triangular_induction.lean"},
          {"polynomial_closure"}, {"rt.unitriangular_factor"}),
        course("rt.unitriangular_factor", "Diagonal-times-unitriangular", "Factor r_matrix as scalar diagonal times a unit lower-triangular matrix.",
          "Use det_mul and det unitriangular = 1.", {"lean/generated/r_triangular_factor.lean"},
          {"polynomial_closure"}, {"rt.permutation_normal_form"}),
        course("rt.permutation_normal_form", "Permutation normal form", "Reverse indices to turn lower bidiagonal into upper triangular form covered by stronger library lemmas.",
          "Reindexed determinant simplifies automatically.", {"lean/generated/r_triangular_reversed.lean"},
          {"polynomial_closure"}, {}),
      },
    },

    q_minor_reduction = {
      objective = "Show the recurrence cofactor minor of q_matrix(n+1) is q_matrix(n).",
      courses = {
        course("qm.shared_erase_index", "Shared erase-index transport", "Reuse the generic erase-index library created for characteristic minors.",
          "Standalone arbitrary-n minor equality compiles.", {"lean/generated/q_minor_shared.lean"},
          {"q_recurrence"}, {"qm.direct_cases", "qm.block_shift"}),
        course("qm.direct_cases", "Direct index cases", "Generate row/column cases: before deletion, at boundary, after deletion; normalize every entry rule branch.",
          "All entry equality goals close under omega/simp/ring.", {"lean/generated/q_minor_cases.lean", "reports/q_minor_case_matrix.md"},
          {"q_recurrence"}, {"qm.block_shift", "qm.recursive_definition"}),
        course("qm.block_shift", "Block shift identity", "Define q(n+1) recursively as a bordered q(n), making the target minor definitionally equal after block projection.",
          "Minor reduction is rfl or a short simp proof.", {"lean/generated/q_recursive_block.lean"},
          {"q_recurrence"}, {"qm.recursive_definition"}),
        course("qm.recursive_definition", "Redefine canonical family recursively", "Introduce a recursively defined qMatrixRec, prove equality to entry-rule qMatrix, and prove recurrence on qMatrixRec.",
          "Universal equality bridge plus easy recursive minor theorem.", {"lean/Ravel/NBonacci/QMatrixRecursive.lean"},
          {"q_recurrence"}, {"qm.permutation_witness"}),
        course("qm.permutation_witness", "Checked permutation witness", "Emit the exact minor-to-q permutation and use determinant invariance, avoiding matrix equality.",
          "Determinants are equal even if entrywise transport is awkward.", {"lua/generated/q_minor_permutation.lua", "lean/generated/q_minor_det_equiv.lean"},
          {"q_recurrence"}, {"qm.desnanot_jacobi"}),
        course("qm.desnanot_jacobi", "Determinant identity route", "Use Dodgson/Desnanot-Jacobi or continuant identities specialized to the banded q family.",
          "Recurrence follows without explicit minor equality.", {"lean/generated/q_continuant_identity.lean"},
          {"q_recurrence"}, {}),
      },
    },

    q_recurrence = {
      objective = "Derive qdet(n+1)=X*qdet(n)+1 from checked matrix structure.",
      courses = {
        course("qr.sparse_laplace", "Sparse Laplace", "Expand a row/column with exactly two nonzero entries and discharge support automatically.",
          "Lean recurrence theorem compiles for arbitrary n.", {"lean/generated/q_recurrence_sparse.lean"},
          {"q_closed_form"}, {"qr.continuant", "qr.block_det"}),
        course("qr.continuant", "Continuant recurrence", "Map q_matrix to a continuant/tridiagonal determinant theorem and specialize coefficients.",
          "Library or project-local continuant theorem yields recurrence.", {"lean/Ravel/Matrix/Continuant.lean"},
          {"q_closed_form"}, {"qr.block_det"}),
        course("qr.block_det", "Bordered block determinant", "Use Schur-complement/bordered determinant expansion where invertibility is not required, specialized symbolically.",
          "Recurrence follows from block determinant identity.", {"lean/generated/q_recurrence_block.lean"},
          {"q_closed_form"}, {"qr.row_operations"}),
        course("qr.row_operations", "Determinant-preserving row operations", "Transform q(n+1) into block triangular form with q(n) and a scalar correction.",
          "Sequence of elementary matrices is Lean-checked.", {"lua/generated/q_row_ops.lua", "lean/generated/q_recurrence_row_ops.lean"},
          {"q_closed_form"}, {"qr.polynomial_evaluation"}),
        course("qr.polynomial_evaluation", "Polynomial evaluation extensionality", "Prove recurrence after evaluation at arbitrary integer/rational x, then recover polynomial equality by extensionality.",
          "Evaluated determinant recurrence plus Polynomial.ext closes.", {"lean/generated/q_recurrence_eval.lean"},
          {"q_closed_form"}, {}),
      },
    },

    q_base = {
      objective = "Establish qdet(2)=1+X without hidden convention mismatch.",
      courses = {
        course("qb.native_decide", "Direct small determinant", "Normalize the 1x1 or 2x2 concrete definition with simp/native_decide as appropriate.",
          "Lean base lemma compiles.", {"lean/generated/q_base_direct.lean"}, {"q_closed_form"}, {"qb.definition_audit"}),
        course("qb.definition_audit", "Boundary convention audit", "Generate n=0,1,2 matrices and compare dimensions/entries against C++ to expose off-by-one conventions.",
          "One canonical convention is documented and all finite tests agree.", {"reports/q_base_conventions.md"}, {"q_closed_form"}, {}),
      },
    },

    q_closed_form = {
      objective = "Solve the determinant recurrence as a finite geometric sum.",
      courses = {
        course("qc.nat_induction", "Nat induction", "Induct from n=2 using recurrence and Finset.sum_range_succ.",
          "Lean proves qdet n = sum range n X^k.", {"lean/generated/q_closed_form_induction.lean"},
          {"polynomial_closure"}, {"qc.shifted_sequence", "qc.generating_function"}),
        course("qc.shifted_sequence", "Shifted-index induction", "Define d m=qdet(m+2), eliminate lower-bound arithmetic, and induct on m.",
          "Proof avoids repeated 2<=n transports.", {"lean/generated/q_closed_form_shifted.lean"},
          {"polynomial_closure"}, {"qc.generating_function"}),
        course("qc.generating_function", "Generating-function identity", "Package recurrence in formal power series and extract coefficients/finite truncation.",
          "Closed form follows from a checked FPS identity.", {"lean/generated/q_closed_form_fps.lean"},
          {"polynomial_closure"}, {"qc.uniqueness"}),
        course("qc.uniqueness", "Recurrence uniqueness", "Prove a generic uniqueness lemma for sequences satisfying d(n+1)=X*d(n)+1 and same base.",
          "Instantiate with determinant sequence and geometric sum sequence.", {"lean/Ravel/Recurrence/FirstOrder.lean"},
          {"polynomial_closure"}, {}),
      },
    },

    characteristic_cofactor_split = {
      objective = "Derive the characteristic determinant split with exact cofactor signs.",
      courses = {
        course("cs.first_row_laplace", "First-row Laplace", "Use sparse first-row expansion and the proven minor maps.",
          "Lean determinant split compiles with exact signs.", {"lean/generated/characteristic_split_laplace.lean"},
          {"polynomial_closure"}, {"cs.first_column", "cs.permutation_block"}),
        course("cs.first_column", "First-column expansion", "Expand the orientation whose signs and minors align more directly with q/r definitions.",
          "Equivalent split with simpler parity proof.", {"lean/generated/characteristic_split_column.lean"},
          {"polynomial_closure"}, {"cs.permutation_block"}),
        course("cs.permutation_block", "Permute then block expand", "Reindex characteristic matrix so the two terms form an obvious bordered block matrix.",
          "Determinant invariance and block formula yield split.", {"lean/generated/characteristic_split_block.lean"},
          {"polynomial_closure"}, {"cs.berkowitz"}),
        course("cs.berkowitz", "Berkowitz recursion", "Generate a division-free characteristic-polynomial certificate via Berkowitz and specialize the companion structure.",
          "Universal coefficient recurrence replaces cofactor sign bookkeeping.", {"lua/generated/berkowitz_certificate.lua", "lean/generated/characteristic_berkowitz.lean"},
          {"polynomial_closure"}, {}),
      },
    },

    polynomial_closure = {
      objective = "Normalize the determinant expression to the canonical n-bonacci characteristic polynomial.",
      courses = {
        course("pc.ring_nf", "ring_nf closure", "Expose finite sums, rewrite parity term, and finish with ring_nf.",
          "Lean accepts canonical equality.", {"lean/generated/polynomial_closure_ring.lean"},
          {"universal_theorem"}, {"pc.coefficient_ext", "pc.telescoping"}),
        course("pc.coefficient_ext", "Coefficient extensionality", "Use Polynomial.ext and prove each coefficient by interval membership cases.",
          "All coefficient goals close with simp/omega.", {"lean/generated/polynomial_closure_coeff.lean"},
          {"universal_theorem"}, {"pc.telescoping"}),
        course("pc.telescoping", "Telescoping sum", "Prove a generic X*sum shift lemma and rewrite the target before normalization.",
          "Small reusable finite-sum lemma closes theorem.", {"lean/Ravel/Polynomial/GeometricShift.lean"},
          {"universal_theorem"}, {"pc.evaluate_many"}),
        course("pc.evaluate_many", "Evaluation extensionality", "Prove equality after arbitrary evaluation in an infinite integral domain and invoke polynomial extensionality.",
          "Evaluation theorem avoids coefficient indexing.", {"lean/generated/polynomial_closure_eval.lean"},
          {"universal_theorem"}, {}),
      },
    },

    universal_theorem = {
      objective = "Compose all lemmas into the arbitrary-n theorem and eliminate all proof holes.",
      courses = {
        course("ut.compose", "Direct composition", "Assemble generated lemmas in dependency order and normalize assumptions.",
          "Pinned Lean kernel accepts theorem for every n>=2.", {"lean/generated/nbonacci_universal.lean"},
          {}, {"ut.minimal_repro", "ut.alternate_statement"}),
        course("ut.minimal_repro", "Minimize failing theorem", "Delta-debug imports, definitions, and rewrites to the smallest failing Lean file; classify elaboration vs mathematics.",
          "Failure reduced to one named lemma or compiler issue.", {"reports/universal_minimization.md", "lean/generated/universal_minimal_repro.lean"},
          {"ut.compose"}, {"ut.alternate_statement"}),
        course("ut.alternate_statement", "Equivalent theorem statement", "Prove a coefficient-list or evaluated form first, then bridge to the public characteristic-polynomial statement.",
          "Equivalent universal theorem plus bridge compiles.", {"lean/generated/nbonacci_universal_bridge.lean"},
          {}, {"ut.independent_generator"}),
        course("ut.independent_generator", "Independent certificate path", "Generate a second proof via Berkowitz/continuant recurrence and compare theorem statements and finite normal forms.",
          "At least one independent universal route is accepted; disagreement becomes a definition audit.", {"lean/generated/nbonacci_universal_independent.lean", "reports/generator_crosscheck.md"},
          {}, {}),
      },
    },
  },
}
