// nbonacci_padic_fingerprint.cpp
//
// p-adic ramification fingerprint for the n-bonacci polynomial
// P_n(x) = x^n - x^{n-1} - ... - x - 1 at small primes p.
//
// The motivation: the simplest covering witness's free-parameter
// vector for n=2..8 has denominators in {1, 2, 3} (verified by
// the C++ covering witness enumerator at n=2..8).  This is a
// 2-and-3-adic signature: the parameters are in Z[1/2, 1/3] but
// not in Z[1/5, 1/7, ...].  The natural p-adic explanation is
// that the dominant root β of P_n(x) is a p-adic unit for
// p ∉ {2, 3} (or that the relevant component of the field
// generated by β is unramified at those primes), so the
// parameters' p-adic denominators stay bounded.  This probe
// verifies the supporting fact: factor P_n(x) mod p for n in
// [2, 8] and p in {2, 3, 5, 7, 11, 13}, and report the
// ramification index e_p (max factor multiplicity) and residue
// degree f_p (min factor degree).  The conjecture is
//
//   { p : e_p > 1 for some n in [2, 8] } ⊂ { 2, 3 }.
//
// i.e. the only primes where P_n is ramified (at any n up to 8)
// are 2 and 3.  If the conjecture holds, the 2/3-adic signature
// of the simplest-witness denominators is explained.
//
// This is a kernel-checked data probe, not a proof.  The output
// is a JSON sidecar at out/nbonacci_padic_fingerprint.json
// (configurable) that the data shaker can consume.
//
// Usage: ./out/nbonacci_padic_fingerprint
//   --n-min=N --n-max=M --primes=2,3,5,7,11,13 [--out=PATH]

#include <algorithm>
#include <cstdio>
#include <fstream>
#include <iostream>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

#include "adelic/dedekind_factorization.hpp"
#include "adelic/fp_poly.hpp"
#include "math/bigint.hpp"
#include "math/poly_discriminant.hpp"
#include "math/poly_z.hpp"
#include "math/primality.hpp"

namespace {

mathlib::PolyZ nbonacci_poly(long long n) {
    // P_n(x) = x^n - x^{n-1} - ... - x - 1, i.e. coeffs[0..n-1] = -1,
    // coeffs[n] = +1.  PolyZ's initializer_list constructor takes
    // ALL the elements, so the list must be exactly the right size.
    switch (n) {
        case 2:  return mathlib::PolyZ({-1, -1, 1});
        case 3:  return mathlib::PolyZ({-1, -1, -1, 1});
        case 4:  return mathlib::PolyZ({-1, -1, -1, -1, 1});
        case 5:  return mathlib::PolyZ({-1, -1, -1, -1, -1, 1});
        case 6:  return mathlib::PolyZ({-1, -1, -1, -1, -1, -1, 1});
        case 7:  return mathlib::PolyZ({-1, -1, -1, -1, -1, -1, -1, 1});
        case 8:  return mathlib::PolyZ({-1, -1, -1, -1, -1, -1, -1, -1, 1});
        default: return mathlib::PolyZ({-1, 1});  // unreachable for n in 2..8
    }
}

mathlib::PolyZ nbonacci_charpoly(long long n) {
    // nbonacciCharpoly n = X + X^2 + ... + X^n - 1, i.e.
    // coeffs[0] = -1, coeffs[1..n] = +1.
    if (n == 2) return mathlib::PolyZ({-1, 1, 1});
    if (n == 3) return mathlib::PolyZ({-1, 1, 1, 1});
    if (n == 4) return mathlib::PolyZ({-1, 1, 1, 1, 1});
    if (n == 5) return mathlib::PolyZ({-1, 1, 1, 1, 1, 1});
    if (n == 6) return mathlib::PolyZ({-1, 1, 1, 1, 1, 1, 1});
    if (n == 7) return mathlib::PolyZ({-1, 1, 1, 1, 1, 1, 1, 1});
    if (n == 8) return mathlib::PolyZ({-1, 1, 1, 1, 1, 1, 1, 1, 1});
    // Fallback (not reached for n in 2..8):
    return mathlib::PolyZ({-1, 1});
}

struct Ramification {
    long long e = 0;          // ramification index (max multiplicity)
    long long f = 0;          // residue degree (min factor degree)
    std::vector<long long> factor_degrees;  // degrees of each distinct irreducible factor
    long long total_factor_count = 0;  // sum of multiplicities
};

Ramification compute_ramification(const mathlib::PolyZ& p, long long prime) {
    adelic::FpPoly f = adelic::reduce_z_to_fp(p, prime);
    std::vector<adelic::FpFactor> factors = adelic::factor_fp(f);
    Ramification r;
    r.e = 0;
    r.f = 0;
    r.total_factor_count = 0;
    for (const auto& fac : factors) {
        long long deg = static_cast<long long>(fac.g.c.size()) - 1;
        if (deg <= 0) continue;  // skip the constant 1 if it appears
        r.factor_degrees.push_back(deg);
        r.e = std::max(r.e, fac.mult);
        if (r.f == 0 || deg < r.f) r.f = deg;
        r.total_factor_count += fac.mult;
    }
    if (r.factor_degrees.empty()) {
        // Polynomial mod p is a nonzero constant or zero; treat as
        // trivial (no ramification information).
        r.e = 0; r.f = 0;
    }
    return r;
}

std::string format_factor_degrees(const std::vector<long long>& ds) {
    std::ostringstream o;
    o << "[";
    for (std::size_t i = 0; i < ds.size(); ++i) {
        if (i) o << ",";
        o << ds[i];
    }
    o << "]";
    return o.str();
}

}  // namespace

int main(int argc, char** argv) {
    long long n_min = 2, n_max = 8;
    std::vector<long long> primes = {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37,
                                     41, 43, 47, 53, 59, 61, 67, 71, 73, 79,
                                     83, 89, 97, 101, 103, 107, 109, 113};
    std::string out_path = "out/nbonacci_padic_fingerprint.json";
    for (int i = 1; i < argc; ++i) {
        std::string a = argv[i];
        auto eq = a.find('=');
        if (eq == std::string::npos) continue;
        std::string k = a.substr(0, eq), v = a.substr(eq + 1);
        if (k == "--n-min") n_min = std::stoll(v);
        else if (k == "--n-max") n_max = std::stoll(v);
        else if (k == "--primes") {
            primes.clear();
            std::stringstream ss(v);
            std::string tok;
            while (std::getline(ss, tok, ',')) primes.push_back(std::stoll(tok));
        }
        else if (k == "--out") out_path = v;
    }
    std::cout << "nbonacci_padic_fingerprint: n in [" << n_min << ", " << n_max
              << "], primes = [";
    for (std::size_t i = 0; i < primes.size(); ++i) {
        if (i) std::cout << ",";
        std::cout << primes[i];
    }
    std::cout << "]\n\n";
    // Two matrices: one for P_n (the n-bonacci polynomial) and one for
    // nbonacciCharpoly n (the reciprocal / companion characteristic).
    std::map<long long, std::map<long long, Ramification>> table_P;
    std::map<long long, std::map<long long, Ramification>> table_C;
    for (long long n = n_min; n <= n_max; ++n) {
        mathlib::PolyZ P = nbonacci_poly(n);
        mathlib::PolyZ C = nbonacci_charpoly(n);
        for (long long p : primes) {
            table_P[n][p] = compute_ramification(P, p);
            table_C[n][p] = compute_ramification(C, p);
        }
    }
    // Print P_n (the n-bonacci polynomial) table
    std::cout << "=== n-bonacci polynomial P_n(x) = x^n - x^{n-1} - ... - x - 1 ===\n";
    std::cout << "        ";
    for (long long p : primes) std::cout << "  p=" << p << "            ";
    std::cout << "\n";
    for (long long n = n_min; n <= n_max; ++n) {
        std::cout << "n=" << n << "  ";
        for (long long p : primes) {
            const auto& r = table_P[n][p];
            char buf[64];
            std::snprintf(buf, sizeof(buf), "e=%lld f=%lld %s    ",
                          r.e, r.f, format_factor_degrees(r.factor_degrees).c_str());
            std::cout << buf;
        }
        std::cout << "\n";
    }
    std::cout << "\n=== nbonacciCharpoly n (reciprocal / companion charpoly) ===\n";
    std::cout << "        ";
    for (long long p : primes) std::cout << "  p=" << p << "            ";
    std::cout << "\n";
    for (long long n = n_min; n <= n_max; ++n) {
        std::cout << "n=" << n << "  ";
        for (long long p : primes) {
            const auto& r = table_C[n][p];
            char buf[64];
            std::snprintf(buf, sizeof(buf), "e=%lld f=%lld %s    ",
                          r.e, r.f, format_factor_degrees(r.factor_degrees).c_str());
            std::cout << buf;
        }
        std::cout << "\n";
    }
    // Auto-flag the ramification-support conjecture:
    //   { p : e_p > 1 for some n in [n_min, n_max] } ⊂ { 2, 3 }.
    std::set<long long> ramified_in_P;
    std::set<long long> ramified_in_C;
    for (long long n = n_min; n <= n_max; ++n) {
        for (long long p : primes) {
            if (table_P[n][p].e > 1) ramified_in_P.insert(p);
            if (table_C[n][p].e > 1) ramified_in_C.insert(p);
        }
    }
    std::cout << "\n=== ramification-support findings ===\n";
    std::cout << "primes with e_p > 1 for some n in P_n (n in 2..8):        {";
    bool first = true;
    for (long long p : ramified_in_P) { if (!first) std::cout << ","; std::cout << p; first = false; }
    std::cout << "}\n";
    std::cout << "primes with e_p > 1 for some n in nbonacciCharpoly: {";
    first = true;
    for (long long p : ramified_in_C) { if (!first) std::cout << ","; std::cout << p; first = false; }
    std::cout << "}\n";
    std::cout << "\n";
    // Per-n ramification breakdown
    std::cout << "Per-n ramification (P_n):\n";
    for (long long n = n_min; n <= n_max; ++n) {
        std::set<long long> ram_for_n;
        for (long long p : primes) {
            if (table_P[n][p].e > 1) ram_for_n.insert(p);
        }
        std::cout << "  n=" << n << ": {";
        first = true;
        for (long long p : ram_for_n) { if (!first) std::cout << ","; std::cout << p; first = false; }
        std::cout << "}\n";
    }
    // Test the original conjecture: is the ramified-prime set a subset
    // of {2, 3}? (i.e., are the 1/2- and 1/3-denominators in the
    // simplest covering witness explained by 2- and 3-adic ramification?)
    std::set<long long> two_three = {2, 3};
    bool P_in_two_three = std::includes(ramified_in_P.begin(),
                                          ramified_in_P.end(),
                                          two_three.begin(), two_three.end());
    std::cout << "\nramified_in_P ⊂ {2, 3}? "
              << (P_in_two_three ? "YES (every ramified prime is 2 or 3)"
                                  : "no (5 and/or 11 also ramify)")
              << "\n";
    std::cout << "ramified_in_nbonacciCharpoly ⊂ {2, 3}? "
              << (std::includes(ramified_in_C.begin(), ramified_in_C.end(),
                                 two_three.begin(), two_three.end()) ? "YES" : "no")
              << "\n";
    // Discriminant of P_n: a single integer per n that contains all
    // p-adic ramification information.  Its p-adic factorization tells
    // us exactly which primes ramify β and to what multiplicity.
    // For n <= 8 the discriminant fits in long long, so we can
    // trial-divide by hand.
    std::cout << "\n=== discriminant of P_n(x) (all p-adic info in one int) ===\n";
    std::map<long long, std::map<long long, long long>>
        disc_factorization;  // n -> (p -> multiplicity) i.e. v_p(disc)
    std::map<long long, long long> disc_value;
    for (long long n = n_min; n <= n_max; ++n) {
        std::vector<long long> f_high_to_low(n + 1);
        f_high_to_low[0] = 1;
        for (std::size_t k = 1; k <= static_cast<std::size_t>(n); ++k)
            f_high_to_low[k] = -1;
        mathlib::BigInt disc = mathlib::poly_discriminant_bigint(f_high_to_low);
        std::string disc_str = mathlib::str(disc);
        disc_value[n] = 0;
        long long disc_ll = 0;
        try { disc_ll = std::stoll(disc_str); }
        catch (...) {
            std::cout << "  n=" << n << "  disc(P_n) = " << disc_str
                      << "  (too large for long long; skipping factorization)\n";
            continue;
        }
        disc_value[n] = disc_ll;
        long long abs_disc = std::abs(disc_ll);
        long long residual = abs_disc;
        bool first_factor = true;
        for (long long p = 2; p * p <= residual && p < 100000; p = mathlib::next_prime(p)) {
            long long v = 0;
            while (residual % p == 0) { residual /= p; ++v; }
            if (v > 0) {
                if (!first_factor) std::cout << " * ";
                std::cout << p << "^" << v;
                first_factor = false;
                disc_factorization[n][p] = v;
            }
        }
        if (residual > 1) {
            if (!first_factor) std::cout << " * ";
            std::cout << residual;
            if (mathlib::is_prime(mathlib::BigInt(residual))) {
                std::cout << " (prime)";
                disc_factorization[n][residual] = 1;
            } else {
                std::cout << " (composite residual)";
            }
            first_factor = false;
        }
        if (first_factor) std::cout << "1";
        std::cout << "\n";
    }
    std::cout << "\n=== ramified primes from discriminant (full p-adic info) ===\n";
    std::set<long long> all_ramified;
    for (auto& np : disc_factorization) {
        for (auto& pv : np.second) {
            all_ramified.insert(pv.first);
        }
    }
    std::cout << "All primes appearing in disc(P_n) for some n in 2..8: {";
    first = true;
    for (long long p : all_ramified) { if (!first) std::cout << ","; std::cout << p; first = false; }
    std::cout << "}\n";
    // Smallest ramified prime per n -- the "next prime" each n
    // graduates into once the prime sieve reaches it.
    std::cout << "\n=== smallest ramified prime per n (from discriminant) ===\n";
    std::cout << "n | smallest ramified prime\n";
    std::cout << "--+-------------------------\n";
    for (long long n = n_min; n <= n_max; ++n) {
        long long smallest = -1;
        for (auto& pv : disc_factorization[n]) {
            if (smallest < 0 || pv.first < smallest) smallest = pv.first;
        }
        std::cout << "  " << n << " | ";
        if (smallest < 0) std::cout << "(disc factorization incomplete)\n";
        else std::cout << smallest << "\n";
    }
    // Graduate: how does the smallest ramified prime scale with n?
    std::cout << "\n=== 'next prime' graduation pattern ===\n";
    std::cout << "n | smallest ramified prime | log10(|disc(P_n)|)\n";
    std::cout << "--+------------------------+-----------------------\n";
    for (long long n = n_min; n <= n_max; ++n) {
        long long smallest = -1;
        for (auto& pv : disc_factorization[n]) {
            if (smallest < 0 || pv.first < smallest) smallest = pv.first;
        }
        long long abs_d = std::abs(disc_value[n]);
        double log_d = 0.0;
        long long tmp = abs_d;
        while (tmp > 0) { log_d += 1.0; tmp /= 10; }
        std::cout << "  " << n << " | ";
        if (smallest < 0) std::cout << "(incomplete) | ";
        else std::cout << smallest << " | ";
        std::cout << log_d << "\n";
    }
    // JSON output
    {
        std::ofstream f(out_path);
        if (!f) {
            std::cerr << "Failed to write " << out_path << "\n";
        } else {
            f << "{";
            f << "\"n_range\":[" << n_min << "," << n_max << "],";
            f << "\"primes\":[";
            for (std::size_t i = 0; i < primes.size(); ++i) {
                if (i) f << ",";
                f << primes[i];
            }
            f << "],";
            f << "\"P_n\":{";
            for (auto it_n = table_P.begin(); it_n != table_P.end(); ++it_n) {
                if (it_n != table_P.begin()) f << ",";
                f << "\"" << it_n->first << "\":{";
                for (auto it_p = it_n->second.begin(); it_p != it_n->second.end(); ++it_p) {
                    if (it_p != it_n->second.begin()) f << ",";
                    f << "\"" << it_p->first << "\":{"
                      << "\"e\":" << it_p->second.e
                      << ",\"f\":" << it_p->second.f
                      << ",\"factor_degrees\":[";
                    for (std::size_t k = 0; k < it_p->second.factor_degrees.size(); ++k) {
                        if (k) f << ",";
                        f << it_p->second.factor_degrees[k];
                    }
                    f << "]}";
                }
                f << "}";
            }
            f << "},";
            f << "\"nbonacciCharpoly\":{";
            for (auto it_n = table_C.begin(); it_n != table_C.end(); ++it_n) {
                if (it_n != table_C.begin()) f << ",";
                f << "\"" << it_n->first << "\":{";
                for (auto it_p = it_n->second.begin(); it_p != it_n->second.end(); ++it_p) {
                    if (it_p != it_n->second.begin()) f << ",";
                    f << "\"" << it_p->first << "\":{"
                      << "\"e\":" << it_p->second.e
                      << ",\"f\":" << it_p->second.f
                      << ",\"factor_degrees\":[";
                    for (std::size_t k = 0; k < it_p->second.factor_degrees.size(); ++k) {
                        if (k) f << ",";
                        f << it_p->second.factor_degrees[k];
                    }
                    f << "]}";
                }
                f << "}";
            }
            f << "},";
            f << "\"ramified_in_P\":[";
            first = true;
            for (long long p : ramified_in_P) { if (!first) f << ","; f << p; first = false; }
            f << "],";
            f << "\"ramified_in_nbonacciCharpoly\":[";
            first = true;
            for (long long p : ramified_in_C) { if (!first) f << ","; f << p; first = false; }
            f << "],";
            f << "\"conjecture_P_subset_two_three\":"
              << (std::includes(ramified_in_P.begin(), ramified_in_P.end(),
                                two_three.begin(), two_three.end()) ? "true" : "false")
              << ",";
            f << "\"conjecture_C_subset_two_three\":"
              << (std::includes(ramified_in_C.begin(), ramified_in_C.end(),
                                two_three.begin(), two_three.end()) ? "true" : "false")
              << "}";
        }
        std::cout << "\nwrote " << out_path << "\n";
    }
    std::cout << "\nnbonacci_padic_fingerprint: complete\n";
    return 0;
}
