// maximal_order.hpp
//
// A (scoped, first-cut) implementation of one round of the
// Pohst-Zassenhaus "Round 2" p-maximal-order enlargement algorithm,
// for when Dedekind's criterion (dedekind_factorization.hpp's
// is_p_maximal) reports that Z[beta] is NOT p-maximal.
//
// docs/ADELIC_TILING_PLAN.md §6 names this exact gap: "Dedekind's
// own non-monogenic cubic" as the textbook example that should be
// added to the factorization layer's test ladder.  This header is
// that follow-up: it builds the enlarged order and verifies (against
// the well-known textbook numbers for that example) that the
// resulting order's discriminant matches the true field discriminant.
//
// SCOPE, STATED HONESTLY: enlarge_order_round2 below implements ONE
// enlargement round using `long long` arithmetic throughout, which is
// enough for the small alphabet sizes (n <= 4) and small primes this
// project's Pisot substitutions actually produce. That function's
// intermediate quantities silently overflow for larger inputs --
// CONFIRMED, not hypothetical: for x^10-2 at p=2, it doesn't just lose
// precision, it throws a spurious "construction invariant violated"
// exception, an int64 overflow masquerading as a math bug (see
// tests/maximal_order_bigint_test.cpp). enlarge_order_round2_bigint,
// near the end of this file, is the arbitrary-precision fix for
// exactly that -- same single-round algorithm, mathlib::BigInt
// throughout the integer-lattice arithmetic.
//
// Both of those still use the MONOGENIC shortcut: factor a single
// defining polynomial mod p and take the ideal generated by its
// squarefree radical, which only works because Z[beta] has a single
// generator. Further down this file, GeneralOrder and
// p_radical_from_structure_constants (Ore's Frobenius method, Cohen
// Sec. 6.1.3) compute the p-radical directly from an order's
// multiplication table instead -- valid for ANY order, monogenic or
// not, which is what round 2 of a genuinely multi-round enlargement
// would need, since the round-1-enlarged order is not in general
// Z[gamma] for any single gamma. enlarge_order_round2_bigint has a
// second overload taking a GeneralOrder for exactly this, cross-
// checked against the monogenic-shortcut path's known-correct answer
// on the trusted textbook case (tests/general_order_radical_test.cpp)
// at p=2, n=3 -- the harder p<=n regime, not the easier one.
//
// That last basis-change step is done too now: structure_constants_
// from_basis_change turns an enlarged order's HNF basis (relative to
// whatever basis the INPUT order had, via Cramer's rule, checked exact
// at every coordinate) into a GeneralOrder in its own right, so the
// chain enlarge -> derive structure constants -> enlarge again
// (general method) -> repeat runs to a fixed point with no defining
// polynomial anywhere past round 1. tests/general_order_radical_test.cpp
// demonstrates the full chain on the trusted textbook case: round 1
// enlarges (disc -2012 -> -503), the derived order's OWN discriminant
// (computed fresh from its own structure constants, not carried
// forward) agrees, and round 2 correctly finds it already 2-maximal.
//
// The chain is exercised on the single-round textbook fixed point. The
// representative quartic now has a verified first multiplier-ring basis
// (-86320 -> -21580); a generic subsequent round in the ramified maximal
// order is deliberately not promoted until its closure criterion is settled.
//
// Algorithm (Cohen, "A Course in Computational Algebraic Number
// Theory", §6.1, specialized to a monogenic starting order Z[beta]):
//
//   1. Factor f(x) mod p (already done by dedekind_factorization.hpp
//      via factor_fp): f_p(x) = prod g_i(x)^{e_i}.
//   2. rad_p(x) = prod g_i(x) (the DISTINCT irreducible factors, each
//      taken once -- the squarefree radical of f_p).
//   3. I = the ideal (p, rad_p(beta)) of Z[beta].  Z[beta]/I is an
//      F_p-vector space; the multiplier ring O' = {x in K :
//      x*I subseteq I} strictly contains Z[beta] whenever Z[beta]
//      was not p-maximal.
//   4. The multiplier-ring condition is the subtle step: for y/p to
//      lie in O' one needs y in the radical ideal J and y*J ⊆ pO.
//      Modulo p this is the intersection J ∩ ann(J), not the image
//      J alone.  Using the image by itself can produce a lattice with
//      the right discriminant quotient but which is not closed under
//      multiplication (the representative quartic caught exactly
//      this failure).  A basis of J ∩ ann(J), lifted to Z, gives the
//      new generators; O' is then Z[beta] + (1/p) * those generators.
//   5. The new order's Z-basis (relative to the power basis
//      1, beta, ..., beta^{n-1}, with an implicit common denominator
//      p) is the Hermite Normal Form of the (n+k) x n integer matrix
//      formed by stacking {p * e_i} (i = 0..n-1) with the lifted
//      annihilator basis vectors (k of them).
//   6. disc(O') = disc(Z[beta]) * (det(H) / p^n)^2, where H is that
//      HNF basis matrix (a standard discriminant-under-basis-change
//      fact).

#pragma once

#include <algorithm>
#include <cstdint>
#include <stdexcept>
#include <vector>

#include "adelic/dedekind_factorization.hpp"
#include "adelic/ideal_arithmetic.hpp"
#include "math/bigint.hpp"
#include "math/poly_discriminant.hpp"
#include "math/poly_z.hpp"

namespace adelic {

// ===================================================================
// Small self-contained F_p and Z linear algebra (long long, small n).
// ===================================================================

// fp_mulmod (multiply two F_p[x] polynomials and reduce modulo a
// third) now lives in fp_poly.hpp -- the single canonical definition,
// available here via dedekind_factorization.hpp's include of it.

// The squarefree radical of f_p mod p: the product of the DISTINCT
// irreducible factors (each taken once, regardless of multiplicity
// in f_p itself).
inline FpPoly squarefree_radical_fp(const std::vector<FpFactor>& factors, long long p) {
    FpPoly rad;
    rad.p = p;
    rad.c = {1};  // start at the constant polynomial 1
    for (const auto& fac : factors) {
        rad = fp_mul(rad, fac.g);
    }
    while (rad.c.size() > 1 && rad.c.back() == 0) rad.c.pop_back();
    return rad;
}

// Coefficient vector of an FpPoly, zero-padded/truncated to length n.
inline std::vector<long long> fp_poly_to_vector(const FpPoly& g, std::size_t n) {
    std::vector<long long> v(n, 0);
    for (std::size_t i = 0; i < g.c.size() && i < n; ++i) v[i] = g.c[i];
    return v;
}

// Basis (via Gaussian elimination mod p) of the F_p-linear SPAN of a
// set of row vectors.  Used for the radical ideal J and for the
// multiplier-ring intersection J ∩ ann(J).
inline std::vector<std::vector<long long>> fp_row_span(
    std::vector<std::vector<long long>> rows, long long p) {
    const std::size_t n = rows.size();
    const std::size_t m = n == 0 ? 0 : rows[0].size();
    std::size_t r = 0;
    for (std::size_t col = 0; col < m && r < n; ++col) {
        std::size_t sel = r;
        while (sel < n && rows[sel][col] % p == 0) ++sel;
        if (sel == n) continue;
        std::swap(rows[r], rows[sel]);
        long long piv = ((rows[r][col] % p) + p) % p;
        long long inv = 0;
        for (long long k = 1; k < p; ++k) {
            if ((piv * k) % p == 1) { inv = k; break; }
        }
        for (std::size_t j = 0; j < m; ++j) rows[r][j] = ((rows[r][j] * inv) % p + p) % p;
        for (std::size_t i = 0; i < n; ++i) {
            if (i == r) continue;
            long long factor = ((rows[i][col] % p) + p) % p;
            if (factor == 0) continue;
            for (std::size_t j = 0; j < m; ++j) {
                rows[i][j] = ((rows[i][j] - factor * rows[r][j]) % p + p * p) % p;
            }
        }
        ++r;
    }
    rows.resize(r);
    return rows;
}

// Kernel (as a list of basis vectors, coefficients in [0, p)) of an
// n x n matrix over F_p, via Gaussian elimination mod p.  `p` must be
// prime (so every nonzero element of F_p is invertible -- used here
// to find pivots).
inline std::vector<std::vector<long long>> fp_matrix_kernel(
    std::vector<std::vector<long long>> M, long long p) {
    const std::size_t n = M.size();
    const std::size_t m = n == 0 ? 0 : M[0].size();
    std::vector<int> pivot_col(n, -1);
    std::size_t row = 0;
    std::vector<int> pivot_of_col(m, -1);
    for (std::size_t col = 0; col < m && row < n; ++col) {
        std::size_t sel = row;
        while (sel < n && M[sel][col] % p == 0) ++sel;
        if (sel == n) continue;  // no pivot in this column
        std::swap(M[row], M[sel]);
        long long piv = ((M[row][col] % p) + p) % p;
        long long inv = 0;
        for (long long k = 1; k < p; ++k) {
            if ((piv * k) % p == 1) { inv = k; break; }
        }
        for (std::size_t j = 0; j < m; ++j) {
            M[row][j] = ((M[row][j] * inv) % p + p) % p;
        }
        for (std::size_t r = 0; r < n; ++r) {
            if (r == row) continue;
            long long factor = ((M[r][col] % p) + p) % p;
            if (factor == 0) continue;
            for (std::size_t j = 0; j < m; ++j) {
                M[r][j] = ((M[r][j] - factor * M[row][j]) % p + p * p) % p;
            }
        }
        pivot_of_col[col] = static_cast<int>(row);
        ++row;
    }
    // Free columns (no pivot) parametrize the kernel.
    std::vector<std::vector<long long>> kernel;
    for (std::size_t col = 0; col < m; ++col) {
        if (pivot_of_col[col] != -1) continue;
        std::vector<long long> vec(m, 0);
        vec[col] = 1;
        for (std::size_t c2 = 0; c2 < m; ++c2) {
            if (pivot_of_col[c2] == -1) continue;
            // Row pivot_of_col[c2] has a 1 in column c2 (after
            // reduction above) and some value in column `col`;
            // solve for that pivot variable.
            long long coeff = M[static_cast<std::size_t>(pivot_of_col[c2])][col];
            vec[c2] = ((-coeff) % p + p) % p;
        }
        kernel.push_back(vec);
    }
    return kernel;
}

// Intersection of two row subspaces of F_p^n.  A vector in the
// intersection has the form u*A = v*B; equivalently it is obtained
// from a kernel vector of the block matrix [A^T | -B^T].
inline std::vector<std::vector<long long>> fp_row_space_intersection(
        const std::vector<std::vector<long long>>& A,
        const std::vector<std::vector<long long>>& B, long long p) {
    const std::size_t n = A.empty() ? (B.empty() ? 0 : B[0].size()) : A[0].size();
    std::vector<std::vector<long long>> block(
        n, std::vector<long long>(A.size() + B.size(), 0));
    for (std::size_t col = 0; col < A.size(); ++col)
        for (std::size_t row = 0; row < n; ++row)
            block[row][col] = ((A[col][row] % p) + p) % p;
    for (std::size_t col = 0; col < B.size(); ++col)
        for (std::size_t row = 0; row < n; ++row)
            block[row][A.size() + col] = ((-B[col][row]) % p + p) % p;
    auto relations = fp_matrix_kernel(block, p);
    std::vector<std::vector<long long>> intersection;
    for (const auto& rel : relations) {
        std::vector<long long> v(n, 0);
        for (std::size_t i = 0; i < A.size(); ++i)
            for (std::size_t j = 0; j < n; ++j)
                v[j] = (v[j] + rel[i] * A[i][j]) % p;
        intersection.push_back(std::move(v));
    }
    return fp_row_span(intersection, p);
}

// Integer Hermite Normal Form (row style, upper triangular) of a
// (rows) x n integer matrix, via elementary row operations
// (long long -- fine for the small entries this module deals with;
// NOT safe for large inputs where intermediate values could
// overflow 64 bits).  Returns the n x n HNF basis (assumes the input
// spans a full-rank n-dimensional lattice, which is guaranteed here
// since the p*e_i rows alone already have full rank n).
//
// Column reduction uses pairwise extended-Euclid combination (NOT
// repeated fixed-pivot subtraction): each combining step strictly
// reduces the COUNT of nonzero rows in the current column by at
// least one, which is what actually guarantees termination -- a
// naive "subtract a multiple of a fixed pivot row" scheme can stall
// forever if a later row's entry is already smaller in magnitude
// than the fixed pivot's (confirmed by an infinite loop during this
// module's first version).
inline std::vector<std::vector<long long>> integer_hnf(
    std::vector<std::vector<long long>> rows, std::size_t n) {
    std::size_t r = 0;
    for (std::size_t col = 0; col < n && r < rows.size(); ++col) {
        for (;;) {
            std::size_t i1 = rows.size();
            for (std::size_t i = r; i < rows.size(); ++i) {
                if (rows[i][col] != 0) { i1 = i; break; }
            }
            if (i1 == rows.size()) break;  // column all-zero below row r
            std::size_t i2 = rows.size();
            for (std::size_t i = i1 + 1; i < rows.size(); ++i) {
                if (rows[i][col] != 0) { i2 = i; break; }
            }
            if (i2 == rows.size()) {
                std::swap(rows[r], rows[i1]);
                break;  // exactly one nonzero row left in this column
            }
            // Extended Euclid on (a, b) = (rows[i1][col], rows[i2][col]):
            // find g = gcd(a,b) = s*a + t*b.
            long long a = rows[i1][col], b = rows[i2][col];
            long long old_r = a, cur_r = b;
            long long old_s = 1, cur_s = 0;
            long long old_t = 0, cur_t = 1;
            while (cur_r != 0) {
                long long q = old_r / cur_r;
                long long tmp_r = old_r - q * cur_r; old_r = cur_r; cur_r = tmp_r;
                long long tmp_s = old_s - q * cur_s; old_s = cur_s; cur_s = tmp_s;
                long long tmp_t = old_t - q * cur_t; old_t = cur_t; cur_t = tmp_t;
            }
            long long g = old_r, s = old_s, t = old_t;
            long long bg = (g != 0) ? b / g : 0;
            long long ag = (g != 0) ? a / g : 0;
            std::vector<long long> new1(n), new2(n);
            for (std::size_t j = 0; j < n; ++j) {
                // new1 has column value s*a + t*b = g.
                new1[j] = s * rows[i1][j] + t * rows[i2][j];
                // new2 has column value (b/g)*a - (a/g)*b = 0.
                new2[j] = bg * rows[i1][j] - ag * rows[i2][j];
            }
            rows[i1] = std::move(new1);
            rows[i2] = std::move(new2);
        }
        if (rows[r][col] < 0) {
            for (std::size_t j = 0; j < n; ++j) rows[r][j] = -rows[r][j];
        }
        if (rows[r][col] != 0) ++r;
    }
    rows.resize(n);
    return rows;
}

// Exact integer determinant via fraction-free (Bareiss) Gaussian
// elimination.  Safe for the small matrices (n <= 5) and small
// entries this module produces; not a general-purpose big-integer
// determinant routine.
inline long long integer_determinant(std::vector<std::vector<long long>> M) {
    const std::size_t n = M.size();
    long long prev_pivot = 1;
    int sign = 1;
    for (std::size_t k = 0; k + 1 < n; ++k) {
        if (M[k][k] == 0) {
            std::size_t sw = k + 1;
            while (sw < n && M[sw][k] == 0) ++sw;
            if (sw == n) return 0;
            std::swap(M[k], M[sw]);
            sign = -sign;
        }
        for (std::size_t i = k + 1; i < n; ++i) {
            for (std::size_t j = k + 1; j < n; ++j) {
                M[i][j] = (M[i][j] * M[k][k] - M[i][k] * M[k][j]) / prev_pivot;
            }
            M[i][k] = 0;
        }
        prev_pivot = M[k][k];
    }
    return sign * (n == 0 ? 1 : M[n - 1][n - 1]);
}

// Discriminant of a monic integer polynomial f of degree n, via the
// Sylvester matrix of (f, f') -- disc(f) = (-1)^{n(n-1)/2} * Res(f,f')
// for monic f.  `long long` throughout; fine for the small
// coefficients this project's characteristic polynomials have.
//
// CONFIRMED OVERFLOW, not just a theoretical risk (2026-07-31,
// math/tests/poly_discriminant_bigint_test.cpp -- now
// tests/poly_discriminant_bigint_test.cpp): for x^n-2, this function
// silently returns a WRONG value starting at n=9 -- not merely unable
// to hold a too-large final answer (disc(x^10-2) is only ~5*10^12,
// nowhere near int64's ~9*10^18 ceiling), but genuinely wrong, because
// Bareiss elimination's INTERMEDIATE entries can overflow even when
// the final determinant fits. Confirmed by disagreement with an
// independent from-scratch closed-form re-derivation of disc(x^n-a)
// (see that test file) AND with math/poly_discriminant.hpp's
// arbitrary-precision poly_discriminant_bigint, which agrees with the
// closed form exactly at every tested n. This project's own current
// Pisot-substitution use (degree <=4, small coefficients) is very
// likely safe -- the Sylvester matrix stays small (at most 7x7) and
// entries stay modest -- but this is now a demonstrated, not
// hypothetical, failure mode for anything of higher degree. Use
// poly_discriminant_bigint for anything beyond this project's own
// small-alphabet substitutions.
inline long long poly_discriminant_ll(const std::vector<long long>& f_high_to_low) {
    // f given highest-degree-first, e.g. x^3 - x^2 - 2x - 8 => {1,-1,-2,-8}.
    long long n = static_cast<long long>(f_high_to_low.size()) - 1;
    std::vector<long long> f = f_high_to_low;
    // f' (derivative), highest-degree-first, degree n-1.
    std::vector<long long> fp;
    for (long long i = 0; i < n; ++i) {
        long long deg = n - i;             // degree of f[i]'s term
        fp.push_back(f[static_cast<std::size_t>(i)] * deg);
    }
    long long m = n - 1;  // degree of f'
    // Sylvester matrix: (n+m) x (n+m) = (2n-1) x (2n-1).
    std::size_t size = static_cast<std::size_t>(n + m);
    std::vector<std::vector<long long>> S(size, std::vector<long long>(size, 0));
    // m rows of shifted f (degree n, so n+1 coeffs), for shift = 0..m-1.
    for (long long shift = 0; shift < m; ++shift) {
        for (std::size_t j = 0; j < f.size(); ++j) {
            S[static_cast<std::size_t>(shift)][static_cast<std::size_t>(shift) + j] = f[j];
        }
    }
    // n rows of shifted f', for shift = 0..n-1.
    for (long long shift = 0; shift < n; ++shift) {
        for (std::size_t j = 0; j < fp.size(); ++j) {
            S[static_cast<std::size_t>(m + shift)][static_cast<std::size_t>(shift) + j] = fp[j];
        }
    }
    long long res = integer_determinant(S);
    long long sign_exp = (n * (n - 1) / 2) % 2;
    return (sign_exp == 0) ? res : -res;
}

// ===================================================================
// The enlargement itself.
// ===================================================================

struct MaximalOrderRound2Result {
    bool enlarged = false;              // false if Z[beta] was ALREADY p-maximal
    std::vector<std::vector<long long>> basis;  // n x n integer basis (implicit
                                                 // denominator p); rows are the
                                                 // new order's basis vectors in
                                                 // terms of 1, beta, ..., beta^{n-1}
    long long det_over_p_n_numerator = 0;  // det(basis) -- disc scales by
                                            // (det(basis)/p^n)^2
    long long disc_before = 0;
    long long disc_after = 0;           // disc(Z[beta]) * (det/p^n)^2
};

// charpoly given highest-degree-first (e.g. x^3 - x^2 - 2x - 8 =>
// {1,-1,-2,-8}); p is the prime where Dedekind's criterion fails.
inline MaximalOrderRound2Result enlarge_order_round2(
    const std::vector<long long>& charpoly_high_to_low, long long p) {
    MaximalOrderRound2Result out;
    long long n = static_cast<long long>(charpoly_high_to_low.size()) - 1;
    out.disc_before = poly_discriminant_ll(charpoly_high_to_low);

    // f_p(x) mod p, LOW-degree-first (dedekind_factorization.hpp's
    // FpPoly convention), monic (charpoly is already monic).
    FpPoly f_p;
    f_p.p = p;
    f_p.c.assign(static_cast<std::size_t>(n + 1), 0);
    for (long long i = 0; i <= n; ++i) {
        long long coeff = charpoly_high_to_low[static_cast<std::size_t>(n - i)];
        long long m = ((coeff % p) + p) % p;
        f_p.c[static_cast<std::size_t>(i)] = m;
    }
    while (f_p.c.size() > 1 && f_p.c.back() == 0) f_p.c.pop_back();

    auto factors = factor_fp(f_p);
    FpPoly rad = squarefree_radical_fp(factors, p);

    // Multiplication-by-rad matrix on A = F_p[x]/(f_p), power basis:
    // column i is rad(x) * x^i mod f_p(x).  The multiplier-ring
    // residues are J ∩ Ann_A(J), where J is the span of these columns.
    std::size_t nn = static_cast<std::size_t>(n);
    std::vector<std::vector<long long>> mult_columns;  // as ROWS, for fp_row_span
    for (std::size_t i = 0; i < nn; ++i) {
        FpPoly xi;
        xi.p = p;
        xi.c.assign(i + 1, 0);
        xi.c[i] = 1;
        FpPoly prod = fp_mulmod(xi, rad, f_p);
        mult_columns.push_back(fp_poly_to_vector(prod, nn));
    }

    auto radical_ideal_basis = fp_row_span(mult_columns, p);
    std::vector<std::vector<long long>> rad_mult(
        nn, std::vector<long long>(nn, 0));
    for (std::size_t col = 0; col < nn; ++col)
        for (std::size_t row = 0; row < nn; ++row)
            rad_mult[row][col] = mult_columns[col][row];
    auto annihilator_basis = fp_matrix_kernel(rad_mult, p);
    auto multiplier_basis = fp_row_space_intersection(
        radical_ideal_basis, annihilator_basis, p);
    if (multiplier_basis.empty()) {
        // Z[beta] was already p-maximal (the nilradical of A is
        // trivial, i.e. f_p is already squarefree -- no repeated
        // factors, the simple sufficient case).
        out.enlarged = false;
        out.disc_after = out.disc_before;
        return out;
    }

    // Stack {p * e_i} with the lifted multiplier basis vectors, then HNF.
    std::vector<std::vector<long long>> rows;
    for (std::size_t i = 0; i < nn; ++i) {
        std::vector<long long> e(nn, 0);
        e[i] = p;
        rows.push_back(e);
    }
    for (const auto& v : multiplier_basis) rows.push_back(v);

    auto H = integer_hnf(rows, nn);
    long long det = integer_determinant(H);

    out.enlarged = true;
    out.basis = H;
    out.det_over_p_n_numerator = det;
    long long p_pow_n = 1;
    for (long long i = 0; i < n; ++i) p_pow_n *= p;
    // disc(O') = disc(Z[beta]) * (det/p^n)^2 = disc(Z[beta]) * det^2 / p^{2n}.
    // Guard: this must divide evenly for a genuine order-enlargement
    // (a bug, not a valid math result, if it doesn't).
    long long numer = out.disc_before * det * det;
    long long denom = p_pow_n * p_pow_n;
    if (numer % denom != 0) {
        throw std::runtime_error("enlarge_order_round2: disc(O') not an integer -- "
                                  "construction invariant violated (bug, not a math result)");
    }
    out.disc_after = numer / denom;
    return out;
}

// ===================================================================
// Arbitrary-precision version, for degrees/discriminants beyond what
// `long long` can safely hold. Same algorithm as enlarge_order_round2
// above (same scope: one enlargement round, from a monogenic starting
// order Z[beta] with a single defining polynomial), ported to
// mathlib::BigInt throughout the integer-lattice arithmetic --
// integer_hnf_bigint here, and integer_determinant_bigint /
// poly_discriminant_bigint reused from math/poly_discriminant.hpp
// (the same functions math/poly_discriminant_bigint_test.cpp already
// validates and which already caught a real overflow bug in this
// file's own poly_discriminant_ll). fp_row_span's mod-p linear algebra
// stays `long long` deliberately -- every value there lives in [0,p),
// never grows, so BigInt would add cost without fixing anything real.
//
// SCOPE, STATED HONESTLY (still): this is arbitrary precision for a
// SINGLE round starting from a monogenic order. It is NOT the general,
// iterate-to-a-fixed-point Round 2 algorithm for an arbitrary
// (possibly non-monogenic) intermediate order -- that needs the
// p-radical computed from an order's structure constants directly
// (Cohen §6.1.3/Ore's method), not from factoring a single defining
// polynomial mod p, since the enlarged order O' in general is no
// longer Z[gamma] for any single gamma. What this DOES provide instead
// of pretending to iterate: `needs_another_round`, a NECESSARY (not
// sufficient) condition check -- if p^2 does not divide disc(O'), p is
// certainly maximal now and no second round is needed; if p^2 DOES
// divide disc(O'), the question is genuinely open (could still be
// maximal, e.g. from ramification) and answering it needs the general
// algorithm this file does not implement. Reporting "don't know, here
// is precisely what would resolve it" is the honest answer here, not
// a guess either way.
struct MaximalOrderRound2ResultBigInt {
    bool enlarged = false;
    std::vector<std::vector<mathlib::BigInt>> basis;
    mathlib::BigInt det_over_p_n_numerator;
    mathlib::BigInt disc_before;
    mathlib::BigInt disc_after;
    // Necessary-condition check only -- see the file comment above.
    // Meaningless (left false) when !enlarged, since then disc_after
    // == disc_before and no enlargement was attempted in the first
    // place.
    bool needs_another_round = false;
};

// Integer HNF, BigInt version of integer_hnf above -- same pairwise
// extended-Euclid combination structure (the same termination
// argument applies verbatim: strictly decreasing nonzero-row count
// per column, independent of entry magnitude).
inline std::vector<std::vector<mathlib::BigInt>> integer_hnf_bigint(
    std::vector<std::vector<mathlib::BigInt>> rows, std::size_t n) {
    std::size_t r = 0;
    for (std::size_t col = 0; col < n && r < rows.size(); ++col) {
        for (;;) {
            std::size_t i1 = rows.size();
            for (std::size_t i = r; i < rows.size(); ++i) {
                if (!mathlib::is_zero(rows[i][col])) { i1 = i; break; }
            }
            if (i1 == rows.size()) break;
            std::size_t i2 = rows.size();
            for (std::size_t i = i1 + 1; i < rows.size(); ++i) {
                if (!mathlib::is_zero(rows[i][col])) { i2 = i; break; }
            }
            if (i2 == rows.size()) {
                std::swap(rows[r], rows[i1]);
                break;
            }
            // Extended Euclid on (a, b) = (rows[i1][col], rows[i2][col]).
            const mathlib::BigInt& a = rows[i1][col];
            const mathlib::BigInt& b = rows[i2][col];
            mathlib::BigInt g, s, t;
            mpz_gcdext(g.get(), s.get(), t.get(), a.get(), b.get());
            mathlib::BigInt bg(0), ag(0);
            if (!mathlib::is_zero(g)) {
                mathlib::divexact(bg, b, g);
                mathlib::divexact(ag, a, g);
            }
            std::vector<mathlib::BigInt> new1(n), new2(n);
            for (std::size_t j = 0; j < n; ++j) {
                mathlib::BigInt t1, t2, t3, t4;
                mathlib::mul(t1, s, rows[i1][j]);
                mathlib::mul(t2, t, rows[i2][j]);
                mathlib::add(new1[j], t1, t2);
                mathlib::mul(t3, bg, rows[i1][j]);
                mathlib::mul(t4, ag, rows[i2][j]);
                mathlib::sub(new2[j], t3, t4);
            }
            rows[i1] = std::move(new1);
            rows[i2] = std::move(new2);
        }
        if (mathlib::sgn(rows[r][col]) < 0) {
            for (std::size_t j = 0; j < n; ++j) mathlib::neg(rows[r][j]);
        }
        if (!mathlib::is_zero(rows[r][col])) ++r;
    }
    rows.resize(n);
    return rows;
}

inline MaximalOrderRound2ResultBigInt enlarge_order_round2_bigint(
    const std::vector<long long>& charpoly_high_to_low, long long p) {
    MaximalOrderRound2ResultBigInt out;
    long long n = static_cast<long long>(charpoly_high_to_low.size()) - 1;
    out.disc_before = mathlib::poly_discriminant_bigint(charpoly_high_to_low);

    FpPoly f_p;
    f_p.p = p;
    f_p.c.assign(static_cast<std::size_t>(n + 1), 0);
    for (long long i = 0; i <= n; ++i) {
        long long coeff = charpoly_high_to_low[static_cast<std::size_t>(n - i)];
        long long m = ((coeff % p) + p) % p;
        f_p.c[static_cast<std::size_t>(i)] = m;
    }
    while (f_p.c.size() > 1 && f_p.c.back() == 0) f_p.c.pop_back();

    auto factors = factor_fp(f_p);
    FpPoly rad = squarefree_radical_fp(factors, p);

    std::size_t nn = static_cast<std::size_t>(n);
    std::vector<std::vector<long long>> mult_columns;
    for (std::size_t i = 0; i < nn; ++i) {
        FpPoly xi;
        xi.p = p;
        xi.c.assign(i + 1, 0);
        xi.c[i] = 1;
        FpPoly prod = fp_mulmod(xi, rad, f_p);
        mult_columns.push_back(fp_poly_to_vector(prod, nn));
    }

    auto radical_ideal_basis = fp_row_span(mult_columns, p);
    if (radical_ideal_basis.empty()) {
        out.enlarged = false;
        out.disc_after = out.disc_before;
        return out;
    }

    // The multiplier ring adds y/p exactly when y lies in the radical
    // ideal J and annihilates J modulo p.  Build multiplication by
    // rad in the power basis and compute J ∩ ann(J); using J alone
    // produces a lattice that need not be an order.
    std::vector<std::vector<long long>> rad_mult(
        nn, std::vector<long long>(nn, 0));
    for (std::size_t col = 0; col < nn; ++col)
        for (std::size_t row = 0; row < nn; ++row)
            rad_mult[row][col] = mult_columns[col][row];
    auto annihilator_basis = fp_matrix_kernel(rad_mult, p);
    auto multiplier_basis = fp_row_space_intersection(
        radical_ideal_basis, annihilator_basis, p);
    if (multiplier_basis.empty()) {
        out.enlarged = false;
        out.disc_after = out.disc_before;
        return out;
    }

    std::vector<std::vector<mathlib::BigInt>> rows;
    for (std::size_t i = 0; i < nn; ++i) {
        std::vector<mathlib::BigInt> e(nn, mathlib::BigInt(0));
        e[i] = mathlib::BigInt(p);
        rows.push_back(std::move(e));
    }
    for (const auto& v : multiplier_basis) {
        std::vector<mathlib::BigInt> row(nn);
        for (std::size_t j = 0; j < nn; ++j) row[j] = mathlib::BigInt(v[j]);
        rows.push_back(std::move(row));
    }

    auto H = integer_hnf_bigint(rows, nn);
    mathlib::BigInt det = mathlib::integer_determinant_bigint(H);

    out.enlarged = true;
    out.basis = H;
    out.det_over_p_n_numerator = det;
    mathlib::BigInt p_pow_n(1);
    for (long long i = 0; i < n; ++i) mathlib::mul_si(p_pow_n, p_pow_n, p);

    mathlib::BigInt numer, tmp;
    mathlib::mul(tmp, det, det);
    mathlib::mul(numer, out.disc_before, tmp);
    mathlib::BigInt denom;
    mathlib::mul(denom, p_pow_n, p_pow_n);

    mathlib::BigInt q, rem;
    mpz_tdiv_qr(q.get(), rem.get(), numer.get(), denom.get());
    if (!mathlib::is_zero(rem)) {
        throw std::runtime_error("enlarge_order_round2_bigint: disc(O') not an integer -- "
                                  "construction invariant violated (bug, not a math result)");
    }
    out.disc_after = q;

    mathlib::BigInt p_sq(p);
    mathlib::mul_si(p_sq, p_sq, p);
    mathlib::BigInt disc_rem;
    mpz_tdiv_r(disc_rem.get(), out.disc_after.get(), p_sq.get());
    out.needs_another_round = mathlib::is_zero(disc_rem);

    return out;
}

// ===================================================================
// General (structure-constants) p-radical and enlargement -- the
// piece enlarge_order_round2/_bigint above deliberately do NOT
// implement, because it is not needed for round 1 (Z[beta] is always
// monogenic) and is more expensive than the shortcut those functions
// use. This is the fallback for round 2 onward, when the previous
// round's enlarged order is no longer guaranteed to be Z[gamma] for
// any single gamma, so there is no single defining polynomial left to
// factor mod p -- the p-radical has to come from the order's own
// multiplication table instead (Cohen "A Course in Computational
// Algebraic Number Theory" Sec. 6.1.3, Ore's method).
//
// COST TRADE-OFF, stated plainly: computing the p-radical this way
// needs an n x n "multiply by w_k" matrix for every basis element
// (O(n) matrix builds, each O(n^2) structure-constant lookups) and a
// Frobenius matrix power (O(log p^k) = O(k log p) matrix
// multiplications, each O(n^3)) -- meaningfully more expensive than
// enlarge_order_round2's single polynomial factorization + one
// multiply-by-rad pass. Use the fast path (enlarge_order_round2 /
// _bigint) whenever a single defining polynomial is available; reach
// for this path only once it genuinely isn't, i.e. from round 2 of a
// multi-round enlargement onward.
// ===================================================================

// An order given by explicit structure constants relative to an
// arbitrary Z-basis w_0..w_{n-1} (NOT necessarily the power basis
// 1,beta,...,beta^{n-1}): mult[i][j] is the coefficient vector of
// w_i * w_j in that same basis. Every order (monogenic or not) has
// such a table; this is the representation the general p-radical
// method needs and enlarge_order_round2's monogenic shortcut avoids
// needing.
struct GeneralOrder {
    long long n = 0;
    std::vector<std::vector<std::vector<mathlib::BigInt>>> mult;  // [i][j][k]
};

// Structure constants for the monogenic order Z[beta], basis
// 1,beta,...,beta^{n-1}: w_i * w_j = beta^{i+j} mod charpoly(beta),
// via the same ring_mul (PolyZ divmod) ideal_arithmetic.hpp already
// uses. The trivial case -- provided so the general machinery below
// can be exercised and cross-checked against enlarge_order_round2's
// known-correct answers before it is ever needed for a genuinely
// non-monogenic order.
inline GeneralOrder monogenic_structure_constants(
        const std::vector<long long>& charpoly_high_to_low) {
    long long n = static_cast<long long>(charpoly_high_to_low.size()) - 1;
    mathlib::PolyZ charpoly;
    charpoly.ensure_size(static_cast<std::size_t>(n) + 1);
    for (long long i = 0; i <= n; ++i) {
        mathlib::set_si(charpoly.coeff(static_cast<std::size_t>(i)),
                         charpoly_high_to_low[static_cast<std::size_t>(n - i)]);
    }
    GeneralOrder O;
    O.n = n;
    O.mult.assign(static_cast<std::size_t>(n),
                   std::vector<std::vector<mathlib::BigInt>>(static_cast<std::size_t>(n)));
    for (long long i = 0; i < n; ++i) {
        mathlib::PolyZ wi;
        wi.ensure_size(static_cast<std::size_t>(i) + 1);
        mathlib::set_si(wi.coeff(static_cast<std::size_t>(i)), 1);
        for (long long j = 0; j < n; ++j) {
            mathlib::PolyZ wj;
            wj.ensure_size(static_cast<std::size_t>(j) + 1);
            mathlib::set_si(wj.coeff(static_cast<std::size_t>(j)), 1);
            mathlib::PolyZ prod = adelic::ring_mul(wi, wj, charpoly);
            std::vector<mathlib::BigInt> coeffs(static_cast<std::size_t>(n), mathlib::BigInt(0));
            for (std::size_t k = 0; k < prod.coeffs_.size() && k < coeffs.size(); ++k) {
                mathlib::set(coeffs[k], prod.coeff(k));
            }
            O.mult[static_cast<std::size_t>(i)][static_cast<std::size_t>(j)] = std::move(coeffs);
        }
    }
    return O;
}

// The F_p matrix of "multiply by w_k" as a linear operator on O/pO:
// column l is the coefficient vector of w_k * w_l mod p.
inline std::vector<std::vector<long long>> matrix_of_multiplication_by(
        const GeneralOrder& O, std::size_t k, long long p) {
    std::size_t n = static_cast<std::size_t>(O.n);
    std::vector<std::vector<long long>> M(n, std::vector<long long>(n, 0));
    for (std::size_t l = 0; l < n; ++l) {
        const auto& coeffs = O.mult[k][l];
        for (std::size_t m = 0; m < n; ++m) {
            mathlib::BigInt r;
            mpz_mod_ui(r.get(), coeffs[m].get(), static_cast<unsigned long>(p));
            M[m][l] = mpz_get_si(r.get());
        }
    }
    return M;
}

// F_p matrix multiplication mod p (small n, long long is fine -- p
// and n are both small enough here that products stay well within
// int64, unlike the integer-lattice arithmetic elsewhere in this
// file).
inline std::vector<std::vector<long long>> fp_matrix_mul(
        const std::vector<std::vector<long long>>& A,
        const std::vector<std::vector<long long>>& B, long long p) {
    std::size_t n = A.size();
    std::vector<std::vector<long long>> C(n, std::vector<long long>(n, 0));
    for (std::size_t i = 0; i < n; ++i)
        for (std::size_t k = 0; k < n; ++k) {
            if (A[i][k] == 0) continue;
            for (std::size_t j = 0; j < n; ++j)
                C[i][j] = (C[i][j] + A[i][k] * B[k][j]) % p;
        }
    return C;
}

// The p-radical I_p/pO of a general order O (any O, monogenic or
// not), via Ore's Frobenius method: build the F_p-linear map
// phi(x) = x^p on O/pO (a well-defined linear map in characteristic p
// by the freshman's-dream identity), find the smallest k with
// p^k >= n, and return ker(phi^k) -- the p-radical is exactly this
// kernel once p^k reaches the algebra's own dimension, since every
// nilpotent element of an n-dimensional algebra is killed by its own
// n-th power at the latest. Valid for EVERY prime p (unlike the
// trace-form shortcut, which needs p > n); the trade-off is the cost
// noted in this section's own header comment above.
inline std::vector<std::vector<long long>> p_radical_from_structure_constants(
        const GeneralOrder& O, long long p) {
    std::size_t n = static_cast<std::size_t>(O.n);
    // Frobenius matrix: column i is w_i^p mod p, built by repeated
    // multiplication-by-w_i (p-1 multiplications; p is assumed small,
    // matching this project's own primes -- 2, 3, 5, ... -- not a
    // general-purpose modular-exponentiation routine).
    std::vector<std::vector<long long>> frob(n, std::vector<long long>(n, 0));
    for (std::size_t i = 0; i < n; ++i) {
        auto mul_by_wi = matrix_of_multiplication_by(O, i, p);
        std::vector<long long> power(n, 0);
        power[i] = 1;  // w_i^1
        for (long long step = 1; step < p; ++step) {
            std::vector<long long> next(n, 0);
            for (std::size_t l = 0; l < n; ++l) {
                if (power[l] == 0) continue;
                for (std::size_t m = 0; m < n; ++m) {
                    next[m] = (next[m] + power[l] * mul_by_wi[m][l]) % p;
                }
            }
            power = std::move(next);
        }
        for (std::size_t m = 0; m < n; ++m) frob[m][i] = power[m];
    }
    // Smallest k with p^k >= n.
    long long pk = 1;
    long long k = 0;
    while (pk < static_cast<long long>(n)) { pk *= p; ++k; }
    if (k == 0) k = 1;  // n<=1 edge case: phi^1 is still the right map to test.
    auto frob_k = frob;
    for (long long step = 1; step < k; ++step) frob_k = fp_matrix_mul(frob_k, frob, p);
    return fp_matrix_kernel(frob_k, p);
}

// Given the nilradical J of O/pO, compute the residue classes that may be
// divided by p in the multiplier ring: J ∩ ann(J).  This is the
// structure-constant analogue of the monogenic Round-2 construction.
inline std::vector<std::vector<long long>> multiplier_basis_from_radical(
        const GeneralOrder& O,
        const std::vector<std::vector<long long>>& radical_basis,
        long long p) {
    const std::size_t n = static_cast<std::size_t>(O.n);
    std::vector<std::vector<long long>> constraints;
    for (const auto& r : radical_basis) {
        // Each row of the block matrix is one coordinate of r*x.
        auto mul = std::vector<std::vector<long long>>(n,
                    std::vector<long long>(n, 0));
        for (std::size_t i = 0; i < n; ++i) {
            auto by_i = matrix_of_multiplication_by(O, i, p);
            for (std::size_t j = 0; j < n; ++j)
                for (std::size_t k = 0; k < n; ++k)
                    mul[j][k] = (mul[j][k] + r[i] * by_i[j][k]) % p;
        }
        for (const auto& row : mul) constraints.push_back(row);
    }
    auto annihilator = fp_matrix_kernel(constraints, p);
    return fp_row_space_intersection(radical_basis, annihilator, p);
}

// Discriminant of a general order from its own structure constants:
// disc(O) = det(Tr(w_i * w_j)), the Gram determinant of the trace
// form on O's own basis (agrees with poly_discriminant_bigint(charpoly)
// for the monogenic power basis -- cross-checked in
// tests/maximal_order_bigint_test.cpp).
inline mathlib::BigInt discriminant_from_structure_constants(const GeneralOrder& O) {
    std::size_t n = static_cast<std::size_t>(O.n);
    // Trace of "multiply by w_k" = sum of the coefficient of w_l in
    // w_k*w_l, over l -- i.e. the l-th diagonal entry of the
    // "multiply by w_k" matrix, summed. Precompute Tr(w_k) for each k.
    std::vector<mathlib::BigInt> trace_of_basis(n, mathlib::BigInt(0));
    for (std::size_t k = 0; k < n; ++k) {
        mathlib::BigInt tr(0);
        for (std::size_t l = 0; l < n; ++l) {
            mathlib::add(tr, tr, O.mult[k][l][l]);
        }
        trace_of_basis[k] = tr;
    }
    // T(w_i,w_j) = Tr(mult-by(w_i*w_j)) = sum_k (w_i*w_j)_k * Tr(w_k),
    // by linearity of trace.
    std::vector<std::vector<mathlib::BigInt>> gram(
        n, std::vector<mathlib::BigInt>(n, mathlib::BigInt(0)));
    for (std::size_t i = 0; i < n; ++i) {
        for (std::size_t j = 0; j < n; ++j) {
            mathlib::BigInt t(0);
            for (std::size_t k = 0; k < n; ++k) {
                mathlib::BigInt term;
                mathlib::mul(term, O.mult[i][j][k], trace_of_basis[k]);
                mathlib::add(t, t, term);
            }
            gram[i][j] = t;
        }
    }
    return mathlib::integer_determinant_bigint(gram);
}

struct GeneralRound2Result {
    bool enlarged = false;
    std::vector<std::vector<mathlib::BigInt>> basis;  // relative to O's OWN basis, denominator p
    mathlib::BigInt disc_before;
    mathlib::BigInt disc_after;
    bool needs_another_round = false;
};

// One enlargement round via the general (structure-constants) method
// -- same "O' = O + (1/p) I_p" construction enlarge_order_round2_bigint
// uses (Cohen Algorithm 6.1.8: this formula is exact for the radical
// specifically, not a shortcut -- the radical's nilpotency is what
// makes the ring-of-multipliers computation collapse to this simple
// form), just fed I_p from the general Frobenius-kernel method above
// instead of the "single generator's multiples" trick that only works
// when O is monogenic.
inline GeneralRound2Result enlarge_order_round2_bigint(const GeneralOrder& O, long long p) {
    GeneralRound2Result out;
    out.disc_before = discriminant_from_structure_constants(O);
    std::size_t n = static_cast<std::size_t>(O.n);

    auto radical_basis = p_radical_from_structure_constants(O, p);
    auto multiplier_basis = multiplier_basis_from_radical(O, radical_basis, p);
    if (multiplier_basis.empty()) {
        out.enlarged = false;
        out.disc_after = out.disc_before;
        return out;
    }

    std::vector<std::vector<mathlib::BigInt>> rows;
    for (std::size_t i = 0; i < n; ++i) {
        std::vector<mathlib::BigInt> e(n, mathlib::BigInt(0));
        e[i] = mathlib::BigInt(p);
        rows.push_back(std::move(e));
    }
    for (const auto& v : multiplier_basis) {
        std::vector<mathlib::BigInt> row(n);
        for (std::size_t j = 0; j < n; ++j) row[j] = mathlib::BigInt(v[j]);
        rows.push_back(std::move(row));
    }

    auto H = integer_hnf_bigint(rows, n);
    mathlib::BigInt det = mathlib::integer_determinant_bigint(H);

    out.enlarged = true;
    out.basis = H;
    mathlib::BigInt p_pow_n(1);
    for (std::size_t i = 0; i < n; ++i) mathlib::mul_si(p_pow_n, p_pow_n, p);

    mathlib::BigInt numer, tmp;
    mathlib::mul(tmp, det, det);
    mathlib::mul(numer, out.disc_before, tmp);
    mathlib::BigInt denom;
    mathlib::mul(denom, p_pow_n, p_pow_n);

    mathlib::BigInt q, rem;
    mpz_tdiv_qr(q.get(), rem.get(), numer.get(), denom.get());
    if (!mathlib::is_zero(rem)) {
        throw std::runtime_error("enlarge_order_round2_bigint(GeneralOrder): disc(O') not an "
                                  "integer -- construction invariant violated (bug, not a "
                                  "math result)");
    }
    out.disc_after = q;

    mathlib::BigInt p_sq(p);
    mathlib::mul_si(p_sq, p_sq, p);
    mathlib::BigInt disc_rem;
    mpz_tdiv_r(disc_rem.get(), out.disc_after.get(), p_sq.get());
    out.needs_another_round = mathlib::is_zero(disc_rem);

    return out;
}

// ===================================================================
// The last piece: deriving a NEW GeneralOrder's own structure
// constants from an enlarged order's HNF basis (as returned in
// enlarge_order_round2_bigint's .basis field, relative to the INPUT
// order's own basis, with implicit denominator p) -- the piece the
// header comment at the top of this file names as the one remaining
// gap between "the general method works" and "a caller can chain
// multiple rounds to a fixed point." With this, that chain is
// complete: enlarge -> derive structure constants for the result ->
// enlarge again (general method, since the result may no longer be
// monogenic) -> repeat until enlarged==false.
// ===================================================================

// Solve Y*H = C for the row vector Y (H an n x n invertible integer
// matrix, C an integer row vector), via Cramer's rule: Y[k] =
// det(H with row k replaced by C) / det(H). Returns Y's numerator
// (i.e. Y*1, already exact) -- callers needing Y/p (this file's own
// use) divide afterward and check exactness themselves, since "exact"
// means different things depending on what the caller is solving for.
inline std::vector<mathlib::BigInt> solve_row_system_cramer(
        const std::vector<std::vector<mathlib::BigInt>>& H,
        const mathlib::BigInt& det_H,
        const std::vector<mathlib::BigInt>& C,
        std::size_t n) {
    std::vector<mathlib::BigInt> Y(n);
    for (std::size_t k = 0; k < n; ++k) {
        auto H_mod = H;
        H_mod[k] = C;
        mathlib::BigInt num = mathlib::integer_determinant_bigint(H_mod);
        mathlib::BigInt q, rem;
        mpz_tdiv_qr(q.get(), rem.get(), num.get(), det_H.get());
        if (!mathlib::is_zero(rem)) {
            throw std::runtime_error("solve_row_system_cramer: Y*H=C has no integer solution -- "
                                      "H is not invertible over this system, or C is not in its "
                                      "row space (bug, not a math result, when H is a genuine "
                                      "order basis)");
        }
        Y[k] = q;
    }
    return Y;
}

// Structure constants for the order with basis rows H[i]/p (relative
// to O's own basis w_0..w_{n-1}), derived from O's structure
// constants. Derivation: if v_i = (1/p) sum_k H[i][k] w_k, then
// v_i*v_j = (1/p^2) sum_m C_m w_m where C_m = sum_{k,l}
// H[i][k]*H[j][l]*O.mult[k][l][m] (exact integers, straight from O's
// own table). Re-expressing that product in the v-basis instead of
// the w-basis needs c_v solving c_v * H = C/p, i.e. (p*c_v) solving
// Y*H=C via Cramer's rule above, then c_v = Y/p -- checked exact at
// every coordinate, since v_i*v_j MUST be an integer combination of
// v_0..v_{n-1} for H to actually be a ring's basis (this is a
// property of the construction, not assumed: enlarge_order_round2_
// bigint's own O'=O+(1/p)I_p formula is exactly what guarantees it).
inline GeneralOrder structure_constants_from_basis_change(
        const GeneralOrder& O,
        const std::vector<std::vector<mathlib::BigInt>>& H,
        long long p) {
    std::size_t n = static_cast<std::size_t>(O.n);
    mathlib::BigInt det_H = mathlib::integer_determinant_bigint(H);
    if (mathlib::is_zero(det_H)) {
        throw std::invalid_argument(
            "structure_constants_from_basis_change: H is singular, not a valid basis");
    }
    GeneralOrder O2;
    O2.n = O.n;
    O2.mult.assign(n, std::vector<std::vector<mathlib::BigInt>>(n));
    mathlib::BigInt p_bi(p);
    for (std::size_t i = 0; i < n; ++i) {
        for (std::size_t j = 0; j < n; ++j) {
            std::vector<mathlib::BigInt> C(n, mathlib::BigInt(0));
            for (std::size_t k = 0; k < n; ++k) {
                if (mathlib::is_zero(H[i][k])) continue;
                for (std::size_t l = 0; l < n; ++l) {
                    if (mathlib::is_zero(H[j][l])) continue;
                    mathlib::BigInt coeff;
                    mathlib::mul(coeff, H[i][k], H[j][l]);
                    for (std::size_t m = 0; m < n; ++m) {
                        mathlib::BigInt term;
                        mathlib::mul(term, coeff, O.mult[k][l][m]);
                        mathlib::add(C[m], C[m], term);
                    }
                }
            }
            // Y solves Y*H = C; c_v = Y/p, exact.
            auto Y = solve_row_system_cramer(H, det_H, C, n);
            std::vector<mathlib::BigInt> c_v(n);
            for (std::size_t k = 0; k < n; ++k) {
                mathlib::BigInt q, rem;
                mpz_tdiv_qr(q.get(), rem.get(), Y[k].get(), p_bi.get());
                if (!mathlib::is_zero(rem)) {
                    throw std::runtime_error(
                        "structure_constants_from_basis_change: v_i*v_j has a non-integer "
                        "coordinate -- construction invariant violated (bug, not a math "
                        "result, if H is a genuine order basis)");
                }
                c_v[k] = q;
            }
            O2.mult[i][j] = std::move(c_v);
        }
    }
    return O2;
}

}  // namespace adelic
