// maximal_order.hpp
//
// A (scoped, first-cut) implementation of one round of the
// Pohst-Zassenhaus "Round 2" p-maximal-order enlargement algorithm,
// for when Dedekind's criterion (dedekind_factorization.hpp's
// is_p_maximal) reports that Z[beta] is NOT p-maximal.
//
// docs/ADELIC_TILING_PLAN.md §6 names this exact gap: "Dedekind's
// own non-monogenic cubic" as the textbook example that should be
// added to the factorization layer's test ladder.  This header is
// that follow-up: it builds the enlarged order and verifies (against
// the well-known textbook numbers for that example) that the
// resulting order's discriminant matches the true field discriminant.
//
// SCOPE, STATED HONESTLY: this implements ONE enlargement round using
// `long long` arithmetic throughout (not mpz_t/exact big-integer
// arithmetic), which is enough for the small alphabet sizes (n <= 4)
// and small primes this project's Pisot substitutions actually
// produce, and enough to resolve the Dedekind cubic test case in a
// single round (as it does classically).  It is NOT a general
// arbitrary-precision, iterate-to-fixed-point Round 2/Round 4
// implementation -- a substitution whose order needs multiple rounds,
// or whose intermediate quantities overflow 64-bit integers, is
// out of scope for this version.  Extending to mpz_t and iterating
// to a fixed point (checking is_p_maximal again on the enlarged
// order and repeating if still not maximal) is the natural next step
// once a concrete Pisot substitution actually needs it.
//
// Algorithm (Cohen, "A Course in Computational Algebraic Number
// Theory", §6.1, specialized to a monogenic starting order Z[beta]):
//
//   1. Factor f(x) mod p (already done by dedekind_factorization.hpp
//      via factor_fp): f_p(x) = prod g_i(x)^{e_i}.
//   2. rad_p(x) = prod g_i(x) (the DISTINCT irreducible factors, each
//      taken once -- the squarefree radical of f_p).
//   3. I = the ideal (p, rad_p(beta)) of Z[beta].  Z[beta]/I is an
//      F_p-vector space; the multiplier ring O' = {x in K :
//      x*I subseteq I} strictly contains Z[beta] whenever Z[beta]
//      was not p-maximal.
//   4. Concretely: I/(p) is the NILRADICAL of A = F_p[x]/(f_p(x)) --
//      the ideal generated by rad_p(theta) in A, i.e. the F_p-linear
//      SPAN (image) of {rad_p(theta) * theta^i : i = 0..n-1}, NOT
//      the annihilator/kernel of multiplication-by-rad_p (a
//      different, generally larger subspace -- conflating the two
//      was this module's first bug, caught by the discriminant
//      sanity check below failing to produce an integer).  A basis
//      of that image, lifted to Z, gives the new generators; O' is
//      then Z[beta] + (1/p) * (those generators).
//   5. The new order's Z-basis (relative to the power basis
//      1, beta, ..., beta^{n-1}, with an implicit common denominator
//      p) is the Hermite Normal Form of the (n+k) x n integer matrix
//      formed by stacking {p * e_i} (i = 0..n-1) with the lifted
//      annihilator basis vectors (k of them).
//   6. disc(O') = disc(Z[beta]) * (det(H) / p^n)^2, where H is that
//      HNF basis matrix (a standard discriminant-under-basis-change
//      fact).

#pragma once

#include <algorithm>
#include <cstdint>
#include <stdexcept>
#include <vector>

#include "adelic/dedekind_factorization.hpp"
#include "math/poly_z.hpp"

namespace adelic {

// ===================================================================
// Small self-contained F_p and Z linear algebra (long long, small n).
// ===================================================================

// Multiply two F_p[x] polynomials and reduce modulo f_p (all
// arithmetic mod p).  Reuses fp_mul (unreduced product) and
// fp_divmod (division with remainder) from dedekind_factorization.hpp.
inline FpPoly fp_mulmod(const FpPoly& a, const FpPoly& b, const FpPoly& f_monic) {
    FpPoly prod = fp_mul(a, b);
    auto dm = fp_divmod(prod, f_monic);
    return dm.second;
}

// The squarefree radical of f_p mod p: the product of the DISTINCT
// irreducible factors (each taken once, regardless of multiplicity
// in f_p itself).
inline FpPoly squarefree_radical_fp(const std::vector<FpFactor>& factors, long long p) {
    FpPoly rad;
    rad.p = p;
    rad.c = {1};  // start at the constant polynomial 1
    for (const auto& fac : factors) {
        rad = fp_mul(rad, fac.g);
    }
    while (rad.c.size() > 1 && rad.c.back() == 0) rad.c.pop_back();
    return rad;
}

// Coefficient vector of an FpPoly, zero-padded/truncated to length n.
inline std::vector<long long> fp_poly_to_vector(const FpPoly& g, std::size_t n) {
    std::vector<long long> v(n, 0);
    for (std::size_t i = 0; i < g.c.size() && i < n; ++i) v[i] = g.c[i];
    return v;
}

// Basis (via Gaussian elimination mod p) of the F_p-linear SPAN of a
// set of row vectors.  Used to compute the nilradical of
// A = F_p[x]/(f_p) as an IDEAL: N = (rad(x))/(f_p(x)) is the IMAGE of
// "multiply by rad", i.e. the span of {rad * x^i : i = 0..n-1} -- NOT
// the kernel/annihilator of that map (a genuinely different F_p-
// subspace; conflating the two was an early bug in this module,
// caught by the disc(O') non-integer invariant check below failing
// on the very first test run -- see maximal_order_test.cpp's
// worked-by-hand derivation in the accompanying commit notes for the
// full by-hand verification that image, not kernel, is correct here).
inline std::vector<std::vector<long long>> fp_row_span(
    std::vector<std::vector<long long>> rows, long long p) {
    const std::size_t n = rows.size();
    const std::size_t m = n == 0 ? 0 : rows[0].size();
    std::size_t r = 0;
    for (std::size_t col = 0; col < m && r < n; ++col) {
        std::size_t sel = r;
        while (sel < n && rows[sel][col] % p == 0) ++sel;
        if (sel == n) continue;
        std::swap(rows[r], rows[sel]);
        long long piv = ((rows[r][col] % p) + p) % p;
        long long inv = 0;
        for (long long k = 1; k < p; ++k) {
            if ((piv * k) % p == 1) { inv = k; break; }
        }
        for (std::size_t j = 0; j < m; ++j) rows[r][j] = ((rows[r][j] * inv) % p + p) % p;
        for (std::size_t i = 0; i < n; ++i) {
            if (i == r) continue;
            long long factor = ((rows[i][col] % p) + p) % p;
            if (factor == 0) continue;
            for (std::size_t j = 0; j < m; ++j) {
                rows[i][j] = ((rows[i][j] - factor * rows[r][j]) % p + p * p) % p;
            }
        }
        ++r;
    }
    rows.resize(r);
    return rows;
}

// Kernel (as a list of basis vectors, coefficients in [0, p)) of an
// n x n matrix over F_p, via Gaussian elimination mod p.  `p` must be
// prime (so every nonzero element of F_p is invertible -- used here
// to find pivots).
inline std::vector<std::vector<long long>> fp_matrix_kernel(
    std::vector<std::vector<long long>> M, long long p) {
    const std::size_t n = M.size();
    const std::size_t m = n == 0 ? 0 : M[0].size();
    std::vector<int> pivot_col(n, -1);
    std::size_t row = 0;
    std::vector<int> pivot_of_col(m, -1);
    for (std::size_t col = 0; col < m && row < n; ++col) {
        std::size_t sel = row;
        while (sel < n && M[sel][col] % p == 0) ++sel;
        if (sel == n) continue;  // no pivot in this column
        std::swap(M[row], M[sel]);
        long long piv = ((M[row][col] % p) + p) % p;
        long long inv = 0;
        for (long long k = 1; k < p; ++k) {
            if ((piv * k) % p == 1) { inv = k; break; }
        }
        for (std::size_t j = 0; j < m; ++j) {
            M[row][j] = ((M[row][j] * inv) % p + p) % p;
        }
        for (std::size_t r = 0; r < n; ++r) {
            if (r == row) continue;
            long long factor = ((M[r][col] % p) + p) % p;
            if (factor == 0) continue;
            for (std::size_t j = 0; j < m; ++j) {
                M[r][j] = ((M[r][j] - factor * M[row][j]) % p + p * p) % p;
            }
        }
        pivot_of_col[col] = static_cast<int>(row);
        ++row;
    }
    // Free columns (no pivot) parametrize the kernel.
    std::vector<std::vector<long long>> kernel;
    for (std::size_t col = 0; col < m; ++col) {
        if (pivot_of_col[col] != -1) continue;
        std::vector<long long> vec(m, 0);
        vec[col] = 1;
        for (std::size_t c2 = 0; c2 < m; ++c2) {
            if (pivot_of_col[c2] == -1) continue;
            // Row pivot_of_col[c2] has a 1 in column c2 (after
            // reduction above) and some value in column `col`;
            // solve for that pivot variable.
            long long coeff = M[static_cast<std::size_t>(pivot_of_col[c2])][col];
            vec[c2] = ((-coeff) % p + p) % p;
        }
        kernel.push_back(vec);
    }
    return kernel;
}

// Integer Hermite Normal Form (row style, upper triangular) of a
// (rows) x n integer matrix, via elementary row operations
// (long long -- fine for the small entries this module deals with;
// NOT safe for large inputs where intermediate values could
// overflow 64 bits).  Returns the n x n HNF basis (assumes the input
// spans a full-rank n-dimensional lattice, which is guaranteed here
// since the p*e_i rows alone already have full rank n).
//
// Column reduction uses pairwise extended-Euclid combination (NOT
// repeated fixed-pivot subtraction): each combining step strictly
// reduces the COUNT of nonzero rows in the current column by at
// least one, which is what actually guarantees termination -- a
// naive "subtract a multiple of a fixed pivot row" scheme can stall
// forever if a later row's entry is already smaller in magnitude
// than the fixed pivot's (confirmed by an infinite loop during this
// module's first version).
inline std::vector<std::vector<long long>> integer_hnf(
    std::vector<std::vector<long long>> rows, std::size_t n) {
    std::size_t r = 0;
    for (std::size_t col = 0; col < n && r < rows.size(); ++col) {
        for (;;) {
            std::size_t i1 = rows.size();
            for (std::size_t i = r; i < rows.size(); ++i) {
                if (rows[i][col] != 0) { i1 = i; break; }
            }
            if (i1 == rows.size()) break;  // column all-zero below row r
            std::size_t i2 = rows.size();
            for (std::size_t i = i1 + 1; i < rows.size(); ++i) {
                if (rows[i][col] != 0) { i2 = i; break; }
            }
            if (i2 == rows.size()) {
                std::swap(rows[r], rows[i1]);
                break;  // exactly one nonzero row left in this column
            }
            // Extended Euclid on (a, b) = (rows[i1][col], rows[i2][col]):
            // find g = gcd(a,b) = s*a + t*b.
            long long a = rows[i1][col], b = rows[i2][col];
            long long old_r = a, cur_r = b;
            long long old_s = 1, cur_s = 0;
            long long old_t = 0, cur_t = 1;
            while (cur_r != 0) {
                long long q = old_r / cur_r;
                long long tmp_r = old_r - q * cur_r; old_r = cur_r; cur_r = tmp_r;
                long long tmp_s = old_s - q * cur_s; old_s = cur_s; cur_s = tmp_s;
                long long tmp_t = old_t - q * cur_t; old_t = cur_t; cur_t = tmp_t;
            }
            long long g = old_r, s = old_s, t = old_t;
            long long bg = (g != 0) ? b / g : 0;
            long long ag = (g != 0) ? a / g : 0;
            std::vector<long long> new1(n), new2(n);
            for (std::size_t j = 0; j < n; ++j) {
                // new1 has column value s*a + t*b = g.
                new1[j] = s * rows[i1][j] + t * rows[i2][j];
                // new2 has column value (b/g)*a - (a/g)*b = 0.
                new2[j] = bg * rows[i1][j] - ag * rows[i2][j];
            }
            rows[i1] = std::move(new1);
            rows[i2] = std::move(new2);
        }
        if (rows[r][col] < 0) {
            for (std::size_t j = 0; j < n; ++j) rows[r][j] = -rows[r][j];
        }
        if (rows[r][col] != 0) ++r;
    }
    rows.resize(n);
    return rows;
}

// Exact integer determinant via fraction-free (Bareiss) Gaussian
// elimination.  Safe for the small matrices (n <= 5) and small
// entries this module produces; not a general-purpose big-integer
// determinant routine.
inline long long integer_determinant(std::vector<std::vector<long long>> M) {
    const std::size_t n = M.size();
    long long prev_pivot = 1;
    int sign = 1;
    for (std::size_t k = 0; k + 1 < n; ++k) {
        if (M[k][k] == 0) {
            std::size_t sw = k + 1;
            while (sw < n && M[sw][k] == 0) ++sw;
            if (sw == n) return 0;
            std::swap(M[k], M[sw]);
            sign = -sign;
        }
        for (std::size_t i = k + 1; i < n; ++i) {
            for (std::size_t j = k + 1; j < n; ++j) {
                M[i][j] = (M[i][j] * M[k][k] - M[i][k] * M[k][j]) / prev_pivot;
            }
            M[i][k] = 0;
        }
        prev_pivot = M[k][k];
    }
    return sign * (n == 0 ? 1 : M[n - 1][n - 1]);
}

// Discriminant of a monic integer polynomial f of degree n, via the
// Sylvester matrix of (f, f') -- disc(f) = (-1)^{n(n-1)/2} * Res(f,f')
// for monic f.  `long long` throughout; fine for the small
// coefficients this project's characteristic polynomials have.
inline long long poly_discriminant_ll(const std::vector<long long>& f_high_to_low) {
    // f given highest-degree-first, e.g. x^3 - x^2 - 2x - 8 => {1,-1,-2,-8}.
    long long n = static_cast<long long>(f_high_to_low.size()) - 1;
    std::vector<long long> f = f_high_to_low;
    // f' (derivative), highest-degree-first, degree n-1.
    std::vector<long long> fp;
    for (long long i = 0; i < n; ++i) {
        long long deg = n - i;             // degree of f[i]'s term
        fp.push_back(f[static_cast<std::size_t>(i)] * deg);
    }
    long long m = n - 1;  // degree of f'
    // Sylvester matrix: (n+m) x (n+m) = (2n-1) x (2n-1).
    std::size_t size = static_cast<std::size_t>(n + m);
    std::vector<std::vector<long long>> S(size, std::vector<long long>(size, 0));
    // m rows of shifted f (degree n, so n+1 coeffs), for shift = 0..m-1.
    for (long long shift = 0; shift < m; ++shift) {
        for (std::size_t j = 0; j < f.size(); ++j) {
            S[static_cast<std::size_t>(shift)][static_cast<std::size_t>(shift) + j] = f[j];
        }
    }
    // n rows of shifted f', for shift = 0..n-1.
    for (long long shift = 0; shift < n; ++shift) {
        for (std::size_t j = 0; j < fp.size(); ++j) {
            S[static_cast<std::size_t>(m + shift)][static_cast<std::size_t>(shift) + j] = fp[j];
        }
    }
    long long res = integer_determinant(S);
    long long sign_exp = (n * (n - 1) / 2) % 2;
    return (sign_exp == 0) ? res : -res;
}

// ===================================================================
// The enlargement itself.
// ===================================================================

struct MaximalOrderRound2Result {
    bool enlarged = false;              // false if Z[beta] was ALREADY p-maximal
    std::vector<std::vector<long long>> basis;  // n x n integer basis (implicit
                                                 // denominator p); rows are the
                                                 // new order's basis vectors in
                                                 // terms of 1, beta, ..., beta^{n-1}
    long long det_over_p_n_numerator = 0;  // det(basis) -- disc scales by
                                            // (det(basis)/p^n)^2
    long long disc_before = 0;
    long long disc_after = 0;           // disc(Z[beta]) * (det/p^n)^2
};

// charpoly given highest-degree-first (e.g. x^3 - x^2 - 2x - 8 =>
// {1,-1,-2,-8}); p is the prime where Dedekind's criterion fails.
inline MaximalOrderRound2Result enlarge_order_round2(
    const std::vector<long long>& charpoly_high_to_low, long long p) {
    MaximalOrderRound2Result out;
    long long n = static_cast<long long>(charpoly_high_to_low.size()) - 1;
    out.disc_before = poly_discriminant_ll(charpoly_high_to_low);

    // f_p(x) mod p, LOW-degree-first (dedekind_factorization.hpp's
    // FpPoly convention), monic (charpoly is already monic).
    FpPoly f_p;
    f_p.p = p;
    f_p.c.assign(static_cast<std::size_t>(n + 1), 0);
    for (long long i = 0; i <= n; ++i) {
        long long coeff = charpoly_high_to_low[static_cast<std::size_t>(n - i)];
        long long m = ((coeff % p) + p) % p;
        f_p.c[static_cast<std::size_t>(i)] = m;
    }
    while (f_p.c.size() > 1 && f_p.c.back() == 0) f_p.c.pop_back();

    auto factors = factor_fp(f_p);
    FpPoly rad = squarefree_radical_fp(factors, p);

    // Multiplication-by-rad matrix on A = F_p[x]/(f_p), power basis:
    // column i is rad(x) * x^i mod f_p(x).  The nilradical N =
    // (rad(theta)) as an IDEAL of A is the F_p-span of these columns
    // (the IMAGE of "multiply by rad" as a linear map) -- NOT the
    // kernel of that map, which is Ann_A(rad) instead (a different,
    // generally larger subspace; see fp_row_span's comment).
    std::size_t nn = static_cast<std::size_t>(n);
    std::vector<std::vector<long long>> mult_columns;  // as ROWS, for fp_row_span
    for (std::size_t i = 0; i < nn; ++i) {
        FpPoly xi;
        xi.p = p;
        xi.c.assign(i + 1, 0);
        xi.c[i] = 1;
        FpPoly prod = fp_mulmod(xi, rad, f_p);
        mult_columns.push_back(fp_poly_to_vector(prod, nn));
    }

    auto nilradical_basis = fp_row_span(mult_columns, p);
    if (nilradical_basis.empty()) {
        // Z[beta] was already p-maximal (the nilradical of A is
        // trivial, i.e. f_p is already squarefree -- no repeated
        // factors, the simple sufficient case).
        out.enlarged = false;
        out.disc_after = out.disc_before;
        return out;
    }

    // Stack {p * e_i} with the lifted nilradical basis vectors, then HNF.
    std::vector<std::vector<long long>> rows;
    for (std::size_t i = 0; i < nn; ++i) {
        std::vector<long long> e(nn, 0);
        e[i] = p;
        rows.push_back(e);
    }
    for (const auto& v : nilradical_basis) rows.push_back(v);

    auto H = integer_hnf(rows, nn);
    long long det = integer_determinant(H);

    out.enlarged = true;
    out.basis = H;
    out.det_over_p_n_numerator = det;
    long long p_pow_n = 1;
    for (long long i = 0; i < n; ++i) p_pow_n *= p;
    // disc(O') = disc(Z[beta]) * (det/p^n)^2 = disc(Z[beta]) * det^2 / p^{2n}.
    // Guard: this must divide evenly for a genuine order-enlargement
    // (a bug, not a valid math result, if it doesn't).
    long long numer = out.disc_before * det * det;
    long long denom = p_pow_n * p_pow_n;
    if (numer % denom != 0) {
        throw std::runtime_error("enlarge_order_round2: disc(O') not an integer -- "
                                  "construction invariant violated (bug, not a math result)");
    }
    out.disc_after = numer / denom;
    return out;
}

}  // namespace adelic
