"""Corrected arithmetic ceilings: eigenvalue module is generated by the
RIGHT PF eigenvector components u_a/(1.u) (true letter frequencies),
not the left. Recompute the ratio hierarchy at LMAX=2^16, N=2^23."""
import math, json
import numpy as np

def expand(subst, n):
    s = np.array([0], dtype=np.int8)
    while len(s) < n:
        s = np.concatenate([np.array(subst[c], dtype=np.int8) for c in s])
    return s[:n]

def both_freqs(subst, nl):
    M = np.zeros((nl, nl))
    for c, w in subst.items():
        for r in w: M[r][c] += 1
    evR, VR = np.linalg.eig(M)
    iR = np.argmax(evR.real)
    u = np.abs(VR[:, iR].real); u /= u.sum()      # RIGHT: true frequencies
    evL, VL = np.linalg.eig(M.T)
    iL = np.argmax(evL.real)
    x = np.abs(VL[:, iL].real); x /= x.sum()      # LEFT: the buggy version
    return u, x

def ceiling(mu, lmax, lmin=33):
    Ls = np.arange(lmax+1)
    worst = np.zeros(lmax+1)
    for m in mu:
        z = (Ls*m) % 1.0
        worst = np.maximum(worst, np.minimum(z, 1-z))
    worst[:lmin] = np.inf
    return np.minimum.accumulate(worst)

def observables(s):
    A0 = 1.0 - 2.0*(s == 0)
    A1 = 1.0 - 2.0*((s == 0) ^ (np.roll(s, -1) == 0))
    return A0[:-1].astype(np.float32), A1[:-1].astype(np.float32)

def corr_all(u, v, lmax):
    n = len(u); size = 1
    while size < n + lmax + 1: size <<= 1
    cc = np.fft.irfft(np.conj(np.fft.rfft(u, size))*np.fft.rfft(v, size), size)
    return (cc[:lmax+1] / (n - np.arange(lmax+1))).astype(np.float64)

SIGNS = [(1,1,1,-1),(1,1,-1,1),(1,-1,1,1),(-1,1,1,1),
         (-1,-1,-1,1),(-1,-1,1,-1),(-1,1,-1,-1),(1,-1,-1,-1)]
def theta_curve(s, lmax, lmin=33):
    A0, A1 = observables(s)
    st = np.stack([corr_all(a, b, lmax) for a in (A0,A1) for b in (A0,A1)])
    smax = np.max(np.stack([g[0]*st[0]+g[1]*st[1]+g[2]*st[2]+g[3]*st[3]
                            for g in SIGNS]), axis=0)
    smax[:lmin] = -np.inf
    return np.maximum.accumulate(smax), smax

SYS = {
 "fibonacci":      ({0:[0,1], 1:[0]}, 2),
 "tribonacci":     ({0:[0,1], 1:[0,2], 2:[0]}, 3),
 "supergolden": ({0:[0,1], 1:[2], 2:[0]}, 3),
 "plastic":        ({0:[1], 1:[2], 2:[0,1]}, 3),
}
N, LMAX = 1 << 23, 1 << 16
out = {}
print(f"{'system':>15} {'freqs(R) vs (L)':>34} {'gap@2^16':>10} "
      f"{'ceilR':>9} {'ratioR':>8} {'(old ratioL)':>12}")
for name, (subst, nl) in SYS.items():
    u, x = both_freqs(subst, nl)
    s = expand(subst, N)
    run, _ = theta_curve(s, LMAX)
    gap = 2 - run[LMAX]
    cR = ceiling(u, LMAX)[LMAX]
    cL = ceiling(x, LMAX)[LMAX]
    print(f"{name:>15} {np.round(u,4)}|{np.round(x,4)} {gap:>10.3e} "
          f"{cR:>9.2e} {gap/cR:>8.1f} {gap/cL:>12.1f}")
    out[name] = {"u": u.tolist(), "x": x.tolist(), "gap": gap,
                 "ceilR": float(cR), "ratioR": gap/cR, "ratioL": gap/cL}
json.dump(out, open("ceiling_corrected_results.json","w"), indent=1)
print("saved -> ceiling_corrected_results.json")
