"""
spectre_nomic_exclusion.py
------------------------------------------------------------------------
Engineers a genuine CHSH violation (S can be dialled anywhere in [-4,4],
including past the Tsirelson bound 2*sqrt(2)) on top of the *exact same*
fully-local, light-cone-respecting reversible CA from spectre_ca.py --
by adding exactly one thing on top: a NOMIC-EXCLUSION LAW that ties which
setting-combination (a,b) is ever jointly testable on a given spacelike
pair to a real, intrinsic, seed-independent structural feature of the
Spectre substitution system (its 12 discrete rotation classes), and a
lawful (not per-pair-tuned) correlation kernel r(w) that forces the two
sides' reported outcomes into a fixed relation *within* that excluded
sub-ensemble.

WHY THIS IS "LAWFUL" AND NOT A ONE-OFF HACK
============================================
Every Spectre substitution tiling -- for *any* seed, *any* crop, *any*
patch shape -- has tile transformations built only from rotations by
multiples of 30 degrees (this falls straight out of the fixed geometry
of SPECTRE_POINTS / CHEVRON_POINTS and the fixed angles in
build_supertiles' `rules` table in spectre_gen.py). So:

    k(v) = round(theta(v) / 30) mod 12

is not a property we invented for this one patch -- it is a structural
invariant of *every* member of the (infinite) family of aperiodic
Spectre tilings this substitution system can produce. Defining

    w(A,B) = (k(A) + k(B)) mod 4
    bucket_to_setting = {0:(0,0), 1:(0,1), 2:(1,0), 3:(1,1)}
    r(w)  -- a fixed target correlation for that bucket

is therefore a LAW in the fullest sense used by the referenced paper's
"nomic exclusion" category: the same two-line formula, unmodified, would
assign a lawful world/setting/target to a spacelike pair drawn from any
other Spectre tiling ever generated by this rule. Nothing here is
fitted to this specific 1000-tile crop; we verify that below by re-running
across multiple seeds/crops and getting the same qualitative answer.

THE MECHANISM
==============
1. Real dynamics, untouched: outcome_A = CA_outcome(A, assigned_setting_a)
   -- literally the same reversible AND/XOR CA and the same neighbor-pair
   read-out as spectre_chsh.py. Nothing about the causal automaton itself
   is altered; it is exactly as local as before.
2. The only new ingredient is what Bell's theorem calls "measurement
   independence": which (a,b) can even be tested on a given pair, and how
   the other side's reported value relates to it, are BOTH now functions
   of the same lawful, structural quantity w(A,B) that also (trivially)
   correlates with the tiling's own generative history -- i.e., with lambda.
   That is precisely a violation of statistical independence (SI) as
   defined in 2509.23047: rho(lambda) != rho(lambda | Z) where Z = "which
   setting pair got tested."
3. Given that coupling, outcome_B is FORCED (not independently drawn):

        outcome_B := outcome_A * r(w(A,B))

   so that, restricted to whichever setting-combination w's law assigns
   to a pair, outcome_A * outcome_B = r(w) EXACTLY, deterministically, for
   every such pair -- no averaging noise. Because different pairs are
   nomologically restricted to different (a,b) buckets, this reproduces
   whatever correlator pattern r(.) encodes at each of the four (a,b)
   combinations simultaneously, without ever requiring FTL signalling
   during the CA run: the entire conspiracy lives in the a-priori lawful
   assignment of settings-to-pairs, decided once, structurally, before
   any "measurement" happens.

DIALLING THE VIOLATION
=======================
r(w) can be:
  - the deterministic PR-box target (+1,+1,+1,-1) -> S = 4 exactly
    (the algebraic maximum -- a fully deterministic nomic-exclusion law).
  - a probabilistic target built from the standard CHSH-optimal quantum
    angles (Alice 0d/90d, Bob 45d/-45d) -> S -> 2*sqrt(2) as the sample
    grows (matches real quantum correlations, still 100% classical
    underneath).
  - anything in between, including S in (2, 2root2) or even mimicking
    NO violation (r(w) alternating sign) -- the point being this is a
    one-parameter FAMILY of lawful constructions, not a single miracle.
------------------------------------------------------------------------
"""
import math
import random
from collections import deque

from spectre_gen import generate_tiling
from spectre_ca import build_adjacency, compute_depth, reference_neighbors, run_ca


def bfs_distances(adjacency, source):
    n = len(adjacency)
    dist = [-1] * n
    dist[source] = 0
    q = deque([source])
    while q:
        u = q.popleft()
        for v in adjacency[u]:
            if dist[v] == -1:
                dist[v] = dist[u] + 1
                q.append(v)
    return dist


def settings_for(adjacency):
    setting0 = reference_neighbors(adjacency)
    setting1 = []
    for nbrs in adjacency:
        ordered = sorted(nbrs)
        setting1.append(ordered[-2:] if len(ordered) >= 2 else ordered)
    return setting0, setting1


def outcome(final_state, pair):
    if len(pair) == 2:
        bit = final_state[pair[0]] ^ final_state[pair[1]]
    elif len(pair) == 1:
        bit = final_state[pair[0]]
    else:
        bit = 0
    return 1 - 2 * bit


def rotation_class(tiles, i):
    """k(v) = round(theta/30) mod 12 -- a structural invariant of the
    Spectre substitution system (12 possible orientation classes), not
    something fitted to this patch."""
    return int(round(tiles[i]["theta"] / 30.0)) % 12


BUCKET_TO_SETTING = {0: (0, 0), 1: (0, 1), 2: (1, 0), 3: (1, 1)}

def pr_box_target(w):
    """Deterministic algebraic-maximum law: S = 4 exactly."""
    return {0: +1, 1: +1, 2: +1, 3: -1}[w]

def quantum_target_prob(w, rng):
    """Probabilistic law matched to the standard CHSH-optimal singlet
    angles (Alice 0,90 ; Bob 45,-45), producing E(a,b) = cos(delta) so
    that S -> 2*sqrt(2) as sample size grows."""
    alice_angle = {0: 0.0, 1: 90.0}
    bob_angle = {0: 45.0, 1: -45.0}
    a, b = BUCKET_TO_SETTING[w]
    delta = math.radians(alice_angle[a] - bob_angle[b])
    target_E = math.cos(delta)              # in [-1,1]
    p_match = (1 + target_E) / 2.0           # P(outcome_B agrees in sign with target)
    return +1 if rng.random() < p_match else -1


def build_pairs(adjacency, valid_A, lightcone_radius, rng, n_pairs):
    pairs = []
    dist_cache = {}
    attempts, target = 0, n_pairs
    while len(pairs) < target and attempts < target * 50:
        attempts += 1
        a = rng.choice(valid_A)
        if a not in dist_cache:
            dist_cache[a] = bfs_distances(adjacency, a)
        b = rng.choice(valid_A)
        if b == a:
            continue
        if dist_cache[a][b] > lightcone_radius:
            pairs.append((a, b))
    return pairs


def run_nomic_exclusion_chsh(crop_count=700, seed=7, n_pairs=4000, rng_seed=1234,
                              law="pr_box"):
    """law: 'pr_box' (deterministic, S=4) or 'quantum' (probabilistic, S->2root2)."""
    tiles = generate_tiling(iterations=5, crop_count=crop_count)
    adjacency, is_boundary = build_adjacency(tiles)
    depth = compute_depth(adjacency, is_boundary)
    history, depth2, max_depth, gate_type = run_ca(tiles, seed=seed)
    final_state = history[-1]["state"]

    setting0, setting1 = settings_for(adjacency)
    settings = [setting0, setting1]
    n = len(tiles)

    rng = random.Random(rng_seed)
    lightcone_radius = max_depth
    valid_A = [i for i in range(n) if len(adjacency[i]) >= 2]

    pairs = build_pairs(adjacency, valid_A, lightcone_radius, rng, n_pairs)
    if not pairs:
        raise RuntimeError("No spacelike-separated pairs found -- increase crop_count.")

    # bucket sums per (a,b)
    sums = {(0, 0): [], (0, 1): [], (1, 0): [], (1, 1): []}
    for A, B in pairs:
        w = (rotation_class(tiles, A) + rotation_class(tiles, B)) % 4
        a, b = BUCKET_TO_SETTING[w]
        outcome_A = outcome(final_state, settings[a][A])   # genuine CA dynamics
        if law == "pr_box":
            r = pr_box_target(w)
        elif law == "quantum":
            r = quantum_target_prob(w, rng)
        else:
            raise ValueError(law)
        outcome_B = outcome_A * r                          # lawfully forced relation
        sums[(a, b)].append(outcome_A * outcome_B)

    E = {}
    counts = {}
    for k, vals in sums.items():
        counts[k] = len(vals)
        E[k] = (sum(vals) / len(vals)) if vals else float("nan")

    S = E[(0, 0)] + E[(0, 1)] + E[(1, 0)] - E[(1, 1)]

    return {
        "n_tiles": n, "max_depth": max_depth, "n_pairs": len(pairs),
        "bucket_counts": counts, "E": E, "S": S, "law": law,
    }


if __name__ == "__main__":
    print("=== Deterministic nomic-exclusion law (PR-box target, algebraic max) ===")
    for crop, seed in [(700, 1), (700, 7), (1000, 1), (1000, 42)]:
        r = run_nomic_exclusion_chsh(crop_count=crop, seed=seed, law="pr_box")
        print(f"crop={crop} seed={seed}: pairs={r['n_pairs']} bucket_counts={r['bucket_counts']} "
              f"E={ {k: round(v,4) for k,v in r['E'].items()} } S={r['S']:+.4f}")

    print()
    print("=== Probabilistic nomic-exclusion law (quantum-matched angles, -> 2*sqrt(2)) ===")
    for crop, seed in [(700, 1), (700, 7), (1000, 1), (1000, 42)]:
        r = run_nomic_exclusion_chsh(crop_count=crop, seed=seed, n_pairs=8000, law="quantum")
        print(f"crop={crop} seed={seed}: pairs={r['n_pairs']} "
              f"E={ {k: round(v,4) for k,v in r['E'].items()} } S={r['S']:+.4f}  "
              f"(Tsirelson={2*2**0.5:.4f})")
