// A finite, reusable "forest" of all parent-role transitions for a canonical
// beta substitution.  This is deliberately independent of any one expansion
// tree: every pair of parent occurrences is recorded once, with its prefix
// defect (the cocycle label) and its source/target role.
#pragma once

#include <cstddef>
#include <algorithm>
#include <map>
#include <numeric>
#include <set>
#include <stdexcept>
#include <string>
#include <functional>
#include <tuple>
#include <vector>

#include "math/qbeta.hpp"
#include "math/sturm.hpp"
#include "ravel/canonical_beta_substitution.hpp"

namespace ravel::proof {

struct CanonicalParentOccurrence {
    long long parent_letter{};
    std::vector<long long> prefix;
};

struct CanonicalParentRoleEdge {
    std::size_t source_role{};
    std::size_t target_role{};
    long long defect{};
    long long left_letter{};
    long long right_letter{};
    long long left_parent{};
    long long right_parent{};
    std::vector<long long> left_prefix;
    std::vector<long long> right_prefix;
};

struct CanonicalParentRoleCatalogue {
    std::vector<long long> digits;
    std::vector<std::vector<long long>> substitution;
    std::vector<std::vector<CanonicalParentOccurrence>> parents;
    std::vector<CanonicalParentRoleEdge> edges;
    std::map<long long, std::size_t> edge_count_by_defect;
    std::set<std::vector<long long>> prefixes;
    std::set<long long> defects;
    std::size_t alphabet_size{};
    std::size_t role_count{};
    long long max_prefix_length{};
    bool proved{};
    std::string obstruction;

    std::size_t role(long long left, long long right) const {
        if (left < 0 || right < 0 || static_cast<std::size_t>(left) >= alphabet_size ||
            static_cast<std::size_t>(right) >= alphabet_size)
            throw std::out_of_range("CanonicalParentRoleCatalogue::role");
        return static_cast<std::size_t>(left) * alphabet_size + static_cast<std::size_t>(right);
    }
};

// A finite obstruction/recognition report for the labelled role forest.  The
// gcd is the subgroup of Z generated by cycle holonomies in an SCC: gcd=0
// means the labels admit an integer potential on that SCC, while gcd>0 is a
// genuine residual twist.  This is a diagnostic invariant, not yet a claim
// that the whole Pisot extension is a group extension.
struct ParentRoleHolonomyComponent {
    std::vector<std::size_t> roles;
    long long holonomy_gcd{};
    bool labels_are_potential{};
};

struct ParentRoleHolonomyReport {
    std::vector<ParentRoleHolonomyComponent> components;
    std::size_t edge_count{};
    std::size_t nontrivial_holonomy_components{};
    bool proved{};
};

struct ParentRoleRegularityReport {
    bool proved{};
    bool label_single_valued{};
    bool occurrence_single_valued{};
    std::size_t max_targets_for_source_label{};
    std::size_t max_occurrences_for_source_target_label{};
    std::size_t branching_source_labels{};
};

struct ParentRoleCompositionWitness {
    std::size_t source_role{};
    std::size_t middle_role{};
    std::size_t target_role{};
    long long first_defect{};
    long long second_defect{};
};

struct ParentRoleCompositionReport {
    bool proved{};
    bool one_step_closed{};
    std::size_t composable_pairs{};
    std::size_t closed_pairs{};
    std::size_t missing_pairs{};
    ParentRoleCompositionWitness first_missing;
};

struct ParentRoleWordClosureReport {
    bool proved{};
    std::size_t max_word_length{};
    std::size_t reachable_source_target_net_states{};
    std::size_t zero_net_pairs{};
    std::size_t zero_net_missing_pairs{};
    std::size_t maximum_zero_net_word_length{};
    std::size_t integer_window_radius{};
    std::size_t integer_window_pairs{};
    std::size_t integer_window_missing_pairs{};
    bool integer_window_complete{};
    struct ZeroNetWitness {
        std::size_t source_role{};
        std::size_t target_role{};
        std::vector<std::size_t> roles;
        std::vector<long long> defects;
    };
    std::vector<ZeroNetWitness> zero_net_witnesses;
    bool zero_net_role_graph_complete{};
    bool zero_net_witnesses_verified{};
};

// Enumerates the finite prefix of the positive word closure.  The state is
// (starting role, current role, accumulated defect); unlike a tree dump this
// quotient deduplicates equal labelled states and therefore exposes the
// actual finite-state cocycle.  The cap is explicit: an incomplete result is
// still useful evidence and is never reported as an infinite theorem.
inline ParentRoleWordClosureReport derive_parent_role_word_closure(
    const CanonicalParentRoleCatalogue& catalogue, std::size_t max_word_length,
    std::size_t integer_window_radius = 0) {
    ParentRoleWordClosureReport out;
    out.max_word_length = max_word_length;
    out.integer_window_radius = integer_window_radius;
    if (!catalogue.proved || max_word_length == 0) return out;
    std::vector<std::vector<std::pair<std::size_t,long long>>> adj(catalogue.role_count);
    for (const auto& edge : catalogue.edges)
        adj[edge.source_role].push_back({edge.target_role, edge.defect});
    const long long net_bound = catalogue.max_prefix_length *
                                static_cast<long long>(max_word_length);
    std::size_t zero_pairs = 0;
    std::size_t maximum_zero_length = 0;
    const auto window_total = catalogue.role_count * catalogue.role_count *
                              (2 * integer_window_radius + 1);
    for (std::size_t source = 0; source < catalogue.role_count; ++source) {
        std::set<std::pair<std::size_t,long long>> seen;
        std::map<std::pair<std::size_t,long long>, std::size_t> depth_of;
        struct Predecessor { std::pair<std::size_t,long long> state; long long defect; };
        std::map<std::pair<std::size_t,long long>, Predecessor> predecessor;
        std::vector<std::pair<std::size_t,long long>> frontier;
        seen.insert({source, 0});
        depth_of[{source, 0}] = 0;
        frontier.push_back({source, 0});
        for (std::size_t depth = 0; depth < max_word_length; ++depth) {
            std::vector<std::pair<std::size_t,long long>> next;
            for (const auto& [role, net] : frontier)
                for (const auto& [target, label] : adj[role]) {
                    const long long new_net = net + label;
                    if (new_net < -net_bound || new_net > net_bound) continue;
                    const auto state = std::make_pair(target, new_net);
                    if (seen.insert(state).second) {
                        depth_of[state] = depth + 1;
                        predecessor[state] = {{role, net}, label};
                        next.push_back(state);
                    }
                }
            frontier.swap(next);
            if (frontier.empty()) break;
        }
        std::set<std::size_t> zero_targets;
        for (const auto& [target, net] : seen) {
            ++out.reachable_source_target_net_states;
            if (net == 0) {
                zero_targets.insert(target);
                maximum_zero_length = std::max(maximum_zero_length, depth_of[{target, net}]);
                ParentRoleWordClosureReport::ZeroNetWitness witness;
                witness.source_role = source;
                witness.target_role = target;
                auto cursor = std::make_pair(target, net);
                witness.roles.push_back(target);
                while (cursor != std::make_pair(source, 0LL)) {
                    const auto& prev = predecessor.at(cursor);
                    witness.defects.push_back(prev.defect);
                    witness.roles.push_back(prev.state.first);
                    cursor = prev.state;
                }
                std::reverse(witness.roles.begin(), witness.roles.end());
                std::reverse(witness.defects.begin(), witness.defects.end());
                out.zero_net_witnesses.push_back(std::move(witness));
            }
        }
        zero_pairs += zero_targets.size();
        for (long long net = -static_cast<long long>(integer_window_radius);
             net <= static_cast<long long>(integer_window_radius); ++net)
            for (std::size_t target = 0; target < catalogue.role_count; ++target)
                if (seen.count({target, net})) ++out.integer_window_pairs;
    }
    out.zero_net_pairs = zero_pairs;
    out.maximum_zero_net_word_length = maximum_zero_length;
    const auto total_pairs = catalogue.role_count * catalogue.role_count;
    out.zero_net_missing_pairs = total_pairs > zero_pairs ? total_pairs - zero_pairs : 0;
    out.integer_window_missing_pairs = window_total > out.integer_window_pairs
        ? window_total - out.integer_window_pairs : 0;
    out.integer_window_complete = (out.integer_window_missing_pairs == 0);
    out.zero_net_role_graph_complete = (out.zero_net_missing_pairs == 0);
    out.zero_net_witnesses_verified = (out.zero_net_witnesses.size() == out.zero_net_pairs);
    for (const auto& witness : out.zero_net_witnesses) {
        long long sum = 0;
        if (witness.roles.size() != witness.defects.size() + 1 ||
            witness.roles.front() != witness.source_role ||
            witness.roles.back() != witness.target_role) {
            out.zero_net_witnesses_verified = false;
            continue;
        }
        for (std::size_t k = 0; k < witness.defects.size(); ++k) {
            sum += witness.defects[k];
            bool edge_exists = false;
            for (const auto& edge : catalogue.edges)
                if (edge.source_role == witness.roles[k] &&
                    edge.target_role == witness.roles[k + 1] &&
                    edge.defect == witness.defects[k]) { edge_exists = true; break; }
            if (!edge_exists) out.zero_net_witnesses_verified = false;
        }
        if (sum != 0) out.zero_net_witnesses_verified = false;
    }
    out.proved = true;
    return out;
}

struct ParentRoleWindowProfile {
    bool proved{};
    std::size_t max_word_length{};
    std::size_t max_radius_tested{};
    std::size_t largest_complete_radius{};
    std::vector<std::size_t> missing_by_radius;
};

struct ParentRoleUnitCycleReport {
    bool proved{};
    std::size_t root_role{};
    std::size_t max_word_length{};
    bool positive_cycle_found{};
    bool negative_cycle_found{};
    std::vector<std::size_t> positive_roles;
    std::vector<long long> positive_defects;
    std::vector<std::size_t> negative_roles;
    std::vector<long long> negative_defects;
};

struct CanonicalUnitCycleSchemaReport {
    bool proved{};
    bool digit_driver_prefix_rule{};
    bool canonical_shape{};
    std::size_t alphabet_size{};
    std::vector<std::size_t> positive_roles;
    std::vector<std::size_t> negative_roles;
    std::string obstruction;
};

// For the canonical Parry parent catalogue (alphabet size n >= 3), the two
// unit cycles have a fixed role shape independent of the digit string:
//   (0,0)->(0,2)->(0,1)->(0,0), defects 0,0,+1
//   (0,0)->(2,0)->(1,0)->(0,0), defects 0,0,-1.
// Checking this shape isolates the reusable combinatorial core behind the
// empirical unit-cycle witnesses.
inline CanonicalUnitCycleSchemaReport derive_canonical_unit_cycle_schema(
    const CanonicalParentRoleCatalogue& catalogue) {
    CanonicalUnitCycleSchemaReport out;
    out.alphabet_size = catalogue.alphabet_size;
    if (!catalogue.proved || catalogue.alphabet_size < 3) {
        out.obstruction = "canonical unit-cycle schema requires alphabet size >= 3";
        return out;
    }
    out.digit_driver_prefix_rule = catalogue.digits.size() >= 3 &&
        catalogue.digits[0] == 1 && catalogue.digits[1] == 0 && catalogue.digits[2] > 0;
    const auto role = [&](std::size_t left, std::size_t right) {
        return left * catalogue.alphabet_size + right;
    };
    out.positive_roles = {role(0,0), role(0,2), role(0,1), role(0,0)};
    out.negative_roles = {role(0,0), role(2,0), role(1,0), role(0,0)};
    const std::vector<long long> positive_defects{0,0,1};
    const std::vector<long long> negative_defects{0,0,-1};
    std::set<std::tuple<std::size_t,std::size_t,long long>> direct;
    for (const auto& edge : catalogue.edges)
        direct.insert({edge.source_role, edge.target_role, edge.defect});
    out.canonical_shape = true;
    for (std::size_t k = 0; k < positive_defects.size(); ++k)
        out.canonical_shape &= direct.count({out.positive_roles[k], out.positive_roles[k + 1], positive_defects[k]}) != 0;
    for (std::size_t k = 0; k < negative_defects.size(); ++k)
        out.canonical_shape &= direct.count({out.negative_roles[k], out.negative_roles[k + 1], negative_defects[k]}) != 0;
    out.proved = out.digit_driver_prefix_rule && out.canonical_shape;
    if (!out.proved) out.obstruction = "canonical unit-cycle role schema not realized";
    return out;
}

// Finds replayable +/-1 closed walks at one common role.  These are the
// generators needed for an integer cocycle: once both exist, powers and
// concatenations give arbitrary net displacement at the root, while the
// zero-net kernel transports the construction to other roles.
inline ParentRoleUnitCycleReport derive_parent_role_unit_cycles(
    const CanonicalParentRoleCatalogue& catalogue, std::size_t max_word_length,
    std::size_t root_role = 0) {
    ParentRoleUnitCycleReport out;
    out.root_role = root_role;
    out.max_word_length = max_word_length;
    if (!catalogue.proved || root_role >= catalogue.role_count || max_word_length == 0) return out;
    std::vector<std::vector<std::pair<std::size_t,long long>>> adj(catalogue.role_count);
    for (const auto& edge : catalogue.edges)
        adj[edge.source_role].push_back({edge.target_role, edge.defect});
    const long long net_bound = catalogue.max_prefix_length *
                                static_cast<long long>(max_word_length);
    std::set<std::pair<std::size_t,long long>> seen;
    std::map<std::pair<std::size_t,long long>,
             std::pair<std::pair<std::size_t,long long>, long long>> predecessor;
    std::vector<std::pair<std::size_t,long long>> frontier{{root_role, 0}};
    seen.insert({root_role, 0});
    auto reconstruct = [&](long long target_net) {
        std::vector<std::size_t> roles{root_role};
        std::vector<long long> defects;
        auto cursor = std::make_pair(root_role, target_net);
        while (cursor != std::make_pair(root_role, 0LL)) {
            const auto& prev = predecessor.at(cursor);
            defects.push_back(prev.second);
            roles.push_back(prev.first.first);
            cursor = prev.first;
        }
        std::reverse(roles.begin(), roles.end());
        std::reverse(defects.begin(), defects.end());
        return std::make_pair(std::move(roles), std::move(defects));
    };
    for (std::size_t depth = 0; depth < max_word_length &&
         (!out.positive_cycle_found || !out.negative_cycle_found); ++depth) {
        std::vector<std::pair<std::size_t,long long>> next;
        for (const auto& [role, net] : frontier) for (const auto& [target, label] : adj[role]) {
            const long long new_net = net + label;
            if (new_net < -net_bound || new_net > net_bound) continue;
            const auto state = std::make_pair(target, new_net);
            if (!seen.insert(state).second) continue;
            predecessor[state] = {{role, net}, label};
            next.push_back(state);
            if (target == root_role && new_net == 1 && !out.positive_cycle_found) {
                auto witness = reconstruct(1);
                out.positive_roles = std::move(witness.first);
                out.positive_defects = std::move(witness.second);
                out.positive_cycle_found = true;
            }
            if (target == root_role && new_net == -1 && !out.negative_cycle_found) {
                auto witness = reconstruct(-1);
                out.negative_roles = std::move(witness.first);
                out.negative_defects = std::move(witness.second);
                out.negative_cycle_found = true;
            }
        }
        frontier.swap(next);
    }
    out.proved = true;
    return out;
}

struct ParentRoleIntegerTransportReport {
    bool proved{};
    std::size_t root_role{};
    std::size_t displacement_radius{};
    std::size_t zero_word_cap{};
    std::size_t transported_words{};
    std::size_t failed_words{};
    std::size_t maximum_transport_word_length{};
    bool every_word_replayed{};
};

struct ParentRoleIntegerSchemeReport {
    bool proved{};
    bool arbitrary_integer_displacement{};
    std::size_t root_role{};
    std::size_t zero_kernel_pairs{};
    std::size_t maximum_zero_path_length{};
    std::size_t positive_cycle_length{};
    std::size_t negative_cycle_length{};
};

// A finite catalogue-level theorem scheme.  The hypotheses are all
// replay-checked finite facts: every ordered role pair has a zero-defect path,
// and one common role has +/-1 closed walks.  Repeating those closed walks
// then constructs a path of any integer net defect between any two roles.
// This does not assert the same hypotheses for an unbounded Pisot family; it
// isolates exactly what the family theorem must establish.
inline ParentRoleIntegerSchemeReport derive_parent_role_integer_scheme(
    const CanonicalParentRoleCatalogue& catalogue, std::size_t zero_word_cap,
    std::size_t cycle_word_cap, std::size_t root_role = 0) {
    ParentRoleIntegerSchemeReport out;
    out.root_role = root_role;
    if (!catalogue.proved) return out;
    const auto closure = derive_parent_role_word_closure(catalogue, zero_word_cap, 0);
    const auto cycles = derive_parent_role_unit_cycles(catalogue, cycle_word_cap, root_role);
    if (!closure.zero_net_role_graph_complete || !closure.zero_net_witnesses_verified ||
        !cycles.positive_cycle_found || !cycles.negative_cycle_found) return out;
    out.zero_kernel_pairs = closure.zero_net_pairs;
    out.maximum_zero_path_length = closure.maximum_zero_net_word_length;
    out.positive_cycle_length = cycles.positive_defects.size();
    out.negative_cycle_length = cycles.negative_defects.size();
    out.arbitrary_integer_displacement = true;
    out.proved = true;
    return out;
}

// Builds the finite transport theorem explicitly: zero-kernel witness
// source -> root, a power of the common +/-1 unit cycle, then a zero-kernel
// witness root -> target.  This is the constructive integer extension at a
// bounded displacement radius; no infinite or asymptotic claim is hidden in
// the report.
inline ParentRoleIntegerTransportReport derive_parent_role_integer_transport(
    const CanonicalParentRoleCatalogue& catalogue, std::size_t zero_word_cap,
    std::size_t displacement_radius, std::size_t root_role = 0) {
    ParentRoleIntegerTransportReport out;
    out.root_role = root_role;
    out.displacement_radius = displacement_radius;
    out.zero_word_cap = zero_word_cap;
    if (!catalogue.proved || root_role >= catalogue.role_count || zero_word_cap == 0) return out;
    const auto closure = derive_parent_role_word_closure(catalogue, zero_word_cap, 0);
    const auto cycles = derive_parent_role_unit_cycles(catalogue, zero_word_cap, root_role);
    if (!closure.zero_net_role_graph_complete || !closure.zero_net_witnesses_verified ||
        !cycles.positive_cycle_found || !cycles.negative_cycle_found) return out;
    using Key = std::pair<std::size_t,std::size_t>;
    std::map<Key, ParentRoleWordClosureReport::ZeroNetWitness> zero_paths;
    for (const auto& witness : closure.zero_net_witnesses)
        zero_paths[{witness.source_role, witness.target_role}] = witness;
    std::set<std::tuple<std::size_t,std::size_t,long long>> direct;
    for (const auto& edge : catalogue.edges)
        direct.insert({edge.source_role, edge.target_role, edge.defect});
    auto append_segment = [](std::vector<std::size_t>& roles,
                             std::vector<long long>& defects,
                             const std::vector<std::size_t>& next_roles,
                             const std::vector<long long>& next_defects) {
        if (next_roles.empty() || next_roles.size() != next_defects.size() + 1) return false;
        if (roles.empty()) {
            roles = next_roles;
            defects = next_defects;
            return true;
        }
        if (roles.back() != next_roles.front()) return false;
        defects.insert(defects.end(), next_defects.begin(), next_defects.end());
        roles.insert(roles.end(), next_roles.begin() + 1, next_roles.end());
        return true;
    };
    out.every_word_replayed = true;
    for (std::size_t source = 0; source < catalogue.role_count; ++source)
        for (std::size_t target = 0; target < catalogue.role_count; ++target)
            for (long long displacement = -static_cast<long long>(displacement_radius);
                 displacement <= static_cast<long long>(displacement_radius); ++displacement) {
                std::vector<std::size_t> roles;
                std::vector<long long> defects;
                const auto& left = zero_paths.at({source, root_role});
                const auto& right = zero_paths.at({root_role, target});
                bool ok = append_segment(roles, defects, left.roles, left.defects);
                const auto& cycle = displacement >= 0 ? cycles.positive_roles : cycles.negative_roles;
                const auto& cycle_defects = displacement >= 0 ? cycles.positive_defects : cycles.negative_defects;
                const auto repetitions = static_cast<std::size_t>(
                    displacement >= 0 ? displacement : -displacement);
                for (std::size_t r = 0; r < repetitions && ok; ++r)
                    ok = append_segment(roles, defects, cycle, cycle_defects);
                ok = ok && append_segment(roles, defects, right.roles, right.defects);
                long long sum = 0;
                if (ok) {
                    for (std::size_t k = 0; k < defects.size(); ++k) {
                        sum += defects[k];
                        if (!direct.count({roles[k], roles[k + 1], defects[k]})) { ok = false; break; }
                    }
                    ok = ok && roles.front() == source && roles.back() == target && sum == displacement;
                }
                ++out.transported_words;
                if (!ok) { ++out.failed_words; out.every_word_replayed = false; }
                else out.maximum_transport_word_length =
                    std::max(out.maximum_transport_word_length, defects.size());
            }
    out.proved = out.every_word_replayed;
    return out;
}

// Profiles the finite displacement window without extrapolating past the
// supplied word cap.  Each entry is independently witness-replayed by the
// underlying closure operation; the profile only summarizes those finite
// certificates and records the first scale at which a state is missing.
inline ParentRoleWindowProfile derive_parent_role_window_profile(
    const CanonicalParentRoleCatalogue& catalogue,
    std::size_t max_word_length, std::size_t max_radius) {
    ParentRoleWindowProfile out;
    out.max_word_length = max_word_length;
    out.max_radius_tested = max_radius;
    if (!catalogue.proved || max_word_length == 0) return out;
    out.missing_by_radius.reserve(max_radius + 1);
    for (std::size_t radius = 0; radius <= max_radius; ++radius) {
        const auto closure = derive_parent_role_word_closure(
            catalogue, max_word_length, radius);
        out.missing_by_radius.push_back(closure.integer_window_missing_pairs);
        if (closure.integer_window_complete)
            out.largest_complete_radius = radius;
    }
    out.proved = true;
    return out;
}

// Checks whether the one-step relation is already closed under composition.
// Usually it is not: generator words are expected to create longer paths.
// Recording the first missing composite makes that distinction explicit and
// prevents mistaking a finite generating relation for a finite group law.
inline ParentRoleCompositionReport derive_parent_role_composition(
    const CanonicalParentRoleCatalogue& catalogue) {
    ParentRoleCompositionReport out;
    if (!catalogue.proved) return out;
    std::set<std::tuple<std::size_t,std::size_t,long long>> direct;
    for (const auto& edge : catalogue.edges)
        direct.insert({edge.source_role, edge.target_role, edge.defect});
    for (const auto& first : catalogue.edges) for (const auto& second : catalogue.edges) {
        if (first.target_role != second.source_role) continue;
        ++out.composable_pairs;
        const auto net = first.defect + second.defect;
        if (direct.count({first.source_role, second.target_role, net})) {
            ++out.closed_pairs;
        } else {
            ++out.missing_pairs;
            if (out.missing_pairs == 1)
                out.first_missing = {first.source_role, first.target_role, second.target_role,
                                     first.defect, second.defect};
        }
    }
    out.one_step_closed = (out.missing_pairs == 0);
    out.proved = true;
    return out;
}

// Tests the first possible group-extension obstruction: whether a defect
// label acts as a function on pair roles.  Parent occurrences are retained,
// so this distinguishes genuine multiplicity from merely having two target
// roles.  A failure is useful data, not an implementation error: it says the
// right theorem must use a relation/sofic correspondence rather than a plain
// action.
inline ParentRoleRegularityReport derive_parent_role_regularity(
    const CanonicalParentRoleCatalogue& catalogue) {
    ParentRoleRegularityReport out;
    if (!catalogue.proved) return out;
    std::map<std::pair<std::size_t,long long>, std::set<std::size_t>> targets;
    std::map<std::tuple<std::size_t,std::size_t,long long>, std::size_t> occurrences;
    for (const auto& edge : catalogue.edges) {
        targets[{edge.source_role, edge.defect}].insert(edge.target_role);
        ++occurrences[{edge.source_role, edge.target_role, edge.defect}];
    }
    out.label_single_valued = true;
    out.occurrence_single_valued = true;
    for (const auto& [key, destinations] : targets) {
        out.max_targets_for_source_label =
            std::max(out.max_targets_for_source_label, destinations.size());
        if (destinations.size() > 1) {
            out.label_single_valued = false;
            ++out.branching_source_labels;
        }
    }
    for (const auto& [_, count] : occurrences) {
        out.max_occurrences_for_source_target_label =
            std::max(out.max_occurrences_for_source_target_label, count);
        if (count > 1) out.occurrence_single_valued = false;
    }
    out.proved = true;
    return out;
}

inline ParentRoleHolonomyReport derive_parent_role_holonomy(
    const CanonicalParentRoleCatalogue& catalogue) {
    ParentRoleHolonomyReport out;
    if (!catalogue.proved) return out;
    const std::size_t N = catalogue.role_count;
    std::vector<std::vector<std::pair<std::size_t,long long>>> adj(N), radj(N);
    for (const auto& edge : catalogue.edges) {
        adj[edge.source_role].push_back({edge.target_role, edge.defect});
        radj[edge.target_role].push_back({edge.source_role, edge.defect});
    }
    out.edge_count = catalogue.edges.size();
    std::vector<char> seen(N, false);
    std::vector<std::size_t> order;
    std::function<void(std::size_t)> dfs1 = [&](std::size_t v) {
        seen[v] = true;
        for (const auto& [w, _] : adj[v]) if (!seen[w]) dfs1(w);
        order.push_back(v);
    };
    for (std::size_t v = 0; v < N; ++v) if (!seen[v]) dfs1(v);
    std::fill(seen.begin(), seen.end(), false);
    std::function<void(std::size_t,std::vector<std::size_t>&)> dfs2 =
        [&](std::size_t v, std::vector<std::size_t>& component) {
            seen[v] = true; component.push_back(v);
            for (const auto& [w, _] : radj[v]) if (!seen[w]) dfs2(w, component);
        };
    while (!order.empty()) {
        const auto root = order.back(); order.pop_back();
        if (seen[root]) continue;
        ParentRoleHolonomyComponent component;
        dfs2(root, component.roles);
        std::set<std::size_t> members(component.roles.begin(), component.roles.end());
        std::vector<char> assigned(N, false);
        std::vector<long long> potential(N, 0);
        long long g = 0;
        for (const auto root_role : component.roles) if (!assigned[root_role]) {
            assigned[root_role] = true;
            std::vector<std::size_t> stack{root_role};
            while (!stack.empty()) {
                const auto v = stack.back(); stack.pop_back();
                for (const auto& [w, label] : adj[v]) {
                    if (!members.count(w)) continue;
                    const long long expected = potential[v] + label;
                    if (!assigned[w]) {
                        assigned[w] = true; potential[w] = expected; stack.push_back(w);
                    } else {
                        g = std::gcd(g, expected - potential[w]);
                    }
                }
            }
        }
        component.holonomy_gcd = g < 0 ? -g : g;
        component.labels_are_potential = (component.holonomy_gcd == 0);
        if (!component.labels_are_potential) ++out.nontrivial_holonomy_components;
        out.components.push_back(std::move(component));
    }
    out.proved = true;
    return out;
}

inline CanonicalParentRoleCatalogue derive_canonical_parent_role_catalogue(
    const mathlib::QBetaRing& R, const mathlib::RootInterval& beta_I) {
    using namespace mathlib;
    CanonicalParentRoleCatalogue out;
    auto ge = exact_greedy_beta_expansion_of_one(R, beta_I, 128);
    if (!ge.terminated && ge.period_len == 0) {
        out.obstruction = "greedy expansion did not terminate or cycle";
        return out;
    }
    out.digits = ge.digits;
    if (ge.terminated || ge.purely_periodic) {
        out.substitution = canonical_beta_substitution_from_digits(out.digits);
    } else {
        std::vector<long long> pre(out.digits.begin(), out.digits.begin() + ge.preperiod_len);
        std::vector<long long> period(out.digits.begin() + ge.preperiod_len, out.digits.end());
        out.substitution = canonical_beta_substitution_eventually_periodic(pre, period);
    }
    out.alphabet_size = out.substitution.size();
    out.role_count = out.alphabet_size * out.alphabet_size;
    out.parents.resize(out.alphabet_size);
    for (std::size_t parent = 0; parent < out.substitution.size(); ++parent) {
        const auto& image = out.substitution[parent];
        for (std::size_t k = 0; k < image.size(); ++k) {
            const auto inner = static_cast<std::size_t>(image[k]);
            if (inner >= out.alphabet_size) {
                out.obstruction = "substitution image contains an out-of-range letter";
                return out;
            }
            std::vector<long long> prefix(image.begin(), image.begin() + static_cast<std::ptrdiff_t>(k));
            out.parents[inner].push_back({static_cast<long long>(parent), prefix});
            out.prefixes.insert(prefix);
            if (static_cast<long long>(prefix.size()) > out.max_prefix_length)
                out.max_prefix_length = static_cast<long long>(prefix.size());
        }
    }
    for (long long left = 0; left < static_cast<long long>(out.alphabet_size); ++left)
        for (long long right = 0; right < static_cast<long long>(out.alphabet_size); ++right)
            for (const auto& lp : out.parents[static_cast<std::size_t>(left)])
                for (const auto& rp : out.parents[static_cast<std::size_t>(right)]) {
                    const long long defect = static_cast<long long>(rp.prefix.size()) -
                                             static_cast<long long>(lp.prefix.size());
                    out.edges.push_back({out.role(left, right), out.role(lp.parent_letter, rp.parent_letter),
                                         defect, left, right, lp.parent_letter, rp.parent_letter,
                                         lp.prefix, rp.prefix});
                    out.defects.insert(defect);
                    ++out.edge_count_by_defect[defect];
                }
    out.proved = true;
    return out;
}

}  // namespace ravel::proof
