// A finite, reusable "forest" of all parent-role transitions for a canonical
// beta substitution.  This is deliberately independent of any one expansion
// tree: every pair of parent occurrences is recorded once, with its prefix
// defect (the cocycle label) and its source/target role.
#pragma once

#include <cstddef>
#include <algorithm>
#include <map>
#include <numeric>
#include <set>
#include <stdexcept>
#include <string>
#include <functional>
#include <tuple>
#include <vector>

#include "math/qbeta.hpp"
#include "math/sturm.hpp"
#include "ravel/canonical_beta_substitution.hpp"

namespace ravel::proof {

struct CanonicalParentOccurrence {
    long long parent_letter{};
    std::vector<long long> prefix;
};

struct CanonicalParentRoleEdge {
    std::size_t source_role{};
    std::size_t target_role{};
    long long defect{};
    long long left_letter{};
    long long right_letter{};
    long long left_parent{};
    long long right_parent{};
    std::vector<long long> left_prefix;
    std::vector<long long> right_prefix;
};

struct CanonicalParentRoleCatalogue {
    std::vector<long long> digits;
    std::vector<std::vector<long long>> substitution;
    std::vector<std::vector<CanonicalParentOccurrence>> parents;
    std::vector<CanonicalParentRoleEdge> edges;
    std::map<long long, std::size_t> edge_count_by_defect;
    std::set<std::vector<long long>> prefixes;
    std::set<long long> defects;
    std::size_t alphabet_size{};
    std::size_t role_count{};
    long long max_prefix_length{};
    bool proved{};
    std::string obstruction;

    std::size_t role(long long left, long long right) const {
        if (left < 0 || right < 0 || static_cast<std::size_t>(left) >= alphabet_size ||
            static_cast<std::size_t>(right) >= alphabet_size)
            throw std::out_of_range("CanonicalParentRoleCatalogue::role");
        return static_cast<std::size_t>(left) * alphabet_size + static_cast<std::size_t>(right);
    }
};

// A finite obstruction/recognition report for the labelled role forest.  The
// gcd is the subgroup of Z generated by cycle holonomies in an SCC: gcd=0
// means the labels admit an integer potential on that SCC, while gcd>0 is a
// genuine residual twist.  This is a diagnostic invariant, not yet a claim
// that the whole Pisot extension is a group extension.
struct ParentRoleHolonomyComponent {
    std::vector<std::size_t> roles;
    long long holonomy_gcd{};
    bool labels_are_potential{};
};

struct ParentRoleHolonomyReport {
    std::vector<ParentRoleHolonomyComponent> components;
    std::size_t edge_count{};
    std::size_t nontrivial_holonomy_components{};
    bool proved{};
};

struct ParentRoleRegularityReport {
    bool proved{};
    bool label_single_valued{};
    bool occurrence_single_valued{};
    std::size_t max_targets_for_source_label{};
    std::size_t max_occurrences_for_source_target_label{};
    std::size_t branching_source_labels{};
};

struct ParentRoleCompositionWitness {
    std::size_t source_role{};
    std::size_t middle_role{};
    std::size_t target_role{};
    long long first_defect{};
    long long second_defect{};
};

struct ParentRoleCompositionReport {
    bool proved{};
    bool one_step_closed{};
    std::size_t composable_pairs{};
    std::size_t closed_pairs{};
    std::size_t missing_pairs{};
    ParentRoleCompositionWitness first_missing;
};

// Checks whether the one-step relation is already closed under composition.
// Usually it is not: generator words are expected to create longer paths.
// Recording the first missing composite makes that distinction explicit and
// prevents mistaking a finite generating relation for a finite group law.
inline ParentRoleCompositionReport derive_parent_role_composition(
    const CanonicalParentRoleCatalogue& catalogue) {
    ParentRoleCompositionReport out;
    if (!catalogue.proved) return out;
    std::set<std::tuple<std::size_t,std::size_t,long long>> direct;
    for (const auto& edge : catalogue.edges)
        direct.insert({edge.source_role, edge.target_role, edge.defect});
    for (const auto& first : catalogue.edges) for (const auto& second : catalogue.edges) {
        if (first.target_role != second.source_role) continue;
        ++out.composable_pairs;
        const auto net = first.defect + second.defect;
        if (direct.count({first.source_role, second.target_role, net})) {
            ++out.closed_pairs;
        } else {
            ++out.missing_pairs;
            if (out.missing_pairs == 1)
                out.first_missing = {first.source_role, first.target_role, second.target_role,
                                     first.defect, second.defect};
        }
    }
    out.one_step_closed = (out.missing_pairs == 0);
    out.proved = true;
    return out;
}

// Tests the first possible group-extension obstruction: whether a defect
// label acts as a function on pair roles.  Parent occurrences are retained,
// so this distinguishes genuine multiplicity from merely having two target
// roles.  A failure is useful data, not an implementation error: it says the
// right theorem must use a relation/sofic correspondence rather than a plain
// action.
inline ParentRoleRegularityReport derive_parent_role_regularity(
    const CanonicalParentRoleCatalogue& catalogue) {
    ParentRoleRegularityReport out;
    if (!catalogue.proved) return out;
    std::map<std::pair<std::size_t,long long>, std::set<std::size_t>> targets;
    std::map<std::tuple<std::size_t,std::size_t,long long>, std::size_t> occurrences;
    for (const auto& edge : catalogue.edges) {
        targets[{edge.source_role, edge.defect}].insert(edge.target_role);
        ++occurrences[{edge.source_role, edge.target_role, edge.defect}];
    }
    out.label_single_valued = true;
    out.occurrence_single_valued = true;
    for (const auto& [key, destinations] : targets) {
        out.max_targets_for_source_label =
            std::max(out.max_targets_for_source_label, destinations.size());
        if (destinations.size() > 1) {
            out.label_single_valued = false;
            ++out.branching_source_labels;
        }
    }
    for (const auto& [_, count] : occurrences) {
        out.max_occurrences_for_source_target_label =
            std::max(out.max_occurrences_for_source_target_label, count);
        if (count > 1) out.occurrence_single_valued = false;
    }
    out.proved = true;
    return out;
}

inline ParentRoleHolonomyReport derive_parent_role_holonomy(
    const CanonicalParentRoleCatalogue& catalogue) {
    ParentRoleHolonomyReport out;
    if (!catalogue.proved) return out;
    const std::size_t N = catalogue.role_count;
    std::vector<std::vector<std::pair<std::size_t,long long>>> adj(N), radj(N);
    for (const auto& edge : catalogue.edges) {
        adj[edge.source_role].push_back({edge.target_role, edge.defect});
        radj[edge.target_role].push_back({edge.source_role, edge.defect});
    }
    out.edge_count = catalogue.edges.size();
    std::vector<char> seen(N, false);
    std::vector<std::size_t> order;
    std::function<void(std::size_t)> dfs1 = [&](std::size_t v) {
        seen[v] = true;
        for (const auto& [w, _] : adj[v]) if (!seen[w]) dfs1(w);
        order.push_back(v);
    };
    for (std::size_t v = 0; v < N; ++v) if (!seen[v]) dfs1(v);
    std::fill(seen.begin(), seen.end(), false);
    std::function<void(std::size_t,std::vector<std::size_t>&)> dfs2 =
        [&](std::size_t v, std::vector<std::size_t>& component) {
            seen[v] = true; component.push_back(v);
            for (const auto& [w, _] : radj[v]) if (!seen[w]) dfs2(w, component);
        };
    while (!order.empty()) {
        const auto root = order.back(); order.pop_back();
        if (seen[root]) continue;
        ParentRoleHolonomyComponent component;
        dfs2(root, component.roles);
        std::set<std::size_t> members(component.roles.begin(), component.roles.end());
        std::vector<char> assigned(N, false);
        std::vector<long long> potential(N, 0);
        long long g = 0;
        for (const auto root_role : component.roles) if (!assigned[root_role]) {
            assigned[root_role] = true;
            std::vector<std::size_t> stack{root_role};
            while (!stack.empty()) {
                const auto v = stack.back(); stack.pop_back();
                for (const auto& [w, label] : adj[v]) {
                    if (!members.count(w)) continue;
                    const long long expected = potential[v] + label;
                    if (!assigned[w]) {
                        assigned[w] = true; potential[w] = expected; stack.push_back(w);
                    } else {
                        g = std::gcd(g, expected - potential[w]);
                    }
                }
            }
        }
        component.holonomy_gcd = g < 0 ? -g : g;
        component.labels_are_potential = (component.holonomy_gcd == 0);
        if (!component.labels_are_potential) ++out.nontrivial_holonomy_components;
        out.components.push_back(std::move(component));
    }
    out.proved = true;
    return out;
}

inline CanonicalParentRoleCatalogue derive_canonical_parent_role_catalogue(
    const mathlib::QBetaRing& R, const mathlib::RootInterval& beta_I) {
    using namespace mathlib;
    CanonicalParentRoleCatalogue out;
    auto ge = exact_greedy_beta_expansion_of_one(R, beta_I, 128);
    if (!ge.terminated && ge.period_len == 0) {
        out.obstruction = "greedy expansion did not terminate or cycle";
        return out;
    }
    out.digits = ge.digits;
    if (ge.terminated || ge.purely_periodic) {
        out.substitution = canonical_beta_substitution_from_digits(out.digits);
    } else {
        std::vector<long long> pre(out.digits.begin(), out.digits.begin() + ge.preperiod_len);
        std::vector<long long> period(out.digits.begin() + ge.preperiod_len, out.digits.end());
        out.substitution = canonical_beta_substitution_eventually_periodic(pre, period);
    }
    out.alphabet_size = out.substitution.size();
    out.role_count = out.alphabet_size * out.alphabet_size;
    out.parents.resize(out.alphabet_size);
    for (std::size_t parent = 0; parent < out.substitution.size(); ++parent) {
        const auto& image = out.substitution[parent];
        for (std::size_t k = 0; k < image.size(); ++k) {
            const auto inner = static_cast<std::size_t>(image[k]);
            if (inner >= out.alphabet_size) {
                out.obstruction = "substitution image contains an out-of-range letter";
                return out;
            }
            std::vector<long long> prefix(image.begin(), image.begin() + static_cast<std::ptrdiff_t>(k));
            out.parents[inner].push_back({static_cast<long long>(parent), prefix});
            out.prefixes.insert(prefix);
            if (static_cast<long long>(prefix.size()) > out.max_prefix_length)
                out.max_prefix_length = static_cast<long long>(prefix.size());
        }
    }
    for (long long left = 0; left < static_cast<long long>(out.alphabet_size); ++left)
        for (long long right = 0; right < static_cast<long long>(out.alphabet_size); ++right)
            for (const auto& lp : out.parents[static_cast<std::size_t>(left)])
                for (const auto& rp : out.parents[static_cast<std::size_t>(right)]) {
                    const long long defect = static_cast<long long>(rp.prefix.size()) -
                                             static_cast<long long>(lp.prefix.size());
                    out.edges.push_back({out.role(left, right), out.role(lp.parent_letter, rp.parent_letter),
                                         defect, left, right, lp.parent_letter, rp.parent_letter,
                                         lp.prefix, rp.prefix});
                    out.defects.insert(defect);
                    ++out.edge_count_by_defect[defect];
                }
    out.proved = true;
    return out;
}

}  // namespace ravel::proof
